Ya vimos en el archivo de exploración que el target cnt es la suma de casual y registered, y cada una de estas categorías tiene una dinámica diferente. Por ejemplo, vimos que los usuarios registered son en general muchos más que los casual. Por eso, haremos un modelo de regresión para predecir la cantidad de usuarios registered por día y otro para los usuarios casual; la predicción de cnt será la suma de las dos anteriores.

Vemos que todos los atributos tienen valores numéricos excepto la fecha, que vuelve a ser representada en los features de día, mes y año. Además, en caso de representar categorías, de todos modos los atributos tienen un orden (las horas del día o los meses del año, por ejemplo). Por otro lado, uno solo de ellos es binario (si es día laborable o no). Incluso varios atributos representan variables reales, como la temperatura o la humedad. En el caso del atributo weatherseat, que tiene 4 categorías, se puede pensar en un "orden" porque un número más alto corresponde a una condición climática más extrema y por lo tanto, creemos, a menor uso de bicicletas.

Como casi todos los features pueden ser considerados como variables numéricas y debemos resolver un problema de regresión, lo abordaremos con una regresión lineal. Algunos atributos pueden ser suficientes para un esquema lineal (como el weathersit, ya que probablemente haya menos ciclistas cuanto más alto ese número); creemos que otros atributos tienen influencia "cuadrática" (pocos ciclistas en los extremos y máximo en algún lugar en el medio). Es el caso de aquellos atributos cuya falta o exceso puede desalentar el uso de bicicletas. Nos referimos, por ejemplo, al viento, la humedad, la temperatura, el mes del año (como vimos en los gráficos, hay más ciclistas en primavera y verano), o incluso la hora del día. Por eso, haremos una regresión lineal con los atributos y con el cuadrado de muchos de ellos, y todo esto por separado para predecir casual y registered.

Descartaremos el atributo fecha porque otros representan el mes y la hora, que estimamos más importantes; el season por ser prácticamente función del mes; el instant por ser un id de registro reemplazable por el índice de la tabla, la temp por ser similar a la atemp (y porque para salir a andar en bicicleta o no es más importante la sensación térmica que la temperatura). Tampoco usaremos el year porque queremos predecir el uso de bicicletas en un día determinado, el cual no debería depender de qué año es. Además, descartaremos el atributo weekday para reducir el riesgo de sobreajuste, y porque creemos que es mucho más importante si es día laborable o no respecto de si es lunes o jueves. No usaremos holiday porque creemos que tendrá una dinámica similar a un fin de semana, y esa información ya está en workingday. Como involucramos además el cuadrado de muchos de los features, usaremos regularización para reducir los parámetros y así prevenir el sobreajuste; probaremos las regularizaciones Ridge y Lasso, aunque creemos que a la primera le irá mejor. Esto se debe a que consideramos importantes a muchos atributos, y la regularización Lasso tiende a dar soluciones con muchos coeficientes muy pequeños o nulos.

Repasamos entonces las funciones de pérdida a utilizar para el desarrollo del modelo, donde MSE es el error cuadrático medio, w es el vector de coeficientes y w' es el vector de coeficientes sin el intercept:

L_ridge = MSE + ||w'||_2^2

L_lasso = MSE + ||w'||_1

En resumen, los atributos utilizados serán: month, month^2, hr, hr^2, workingday, weathersit, atemp, atemp^2, hum, hum^2, windspeed, windspeed^2. Para evaluar el desempeño de los modelos usaremos el score R^2.

Generamos ahora la nueva base de datos con todos los atributos a utilizar (originales y artificiales).

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

In [8]:
from ucimlrepo import fetch_ucirepo
def get_data():
    ds = fetch_ucirepo(id=275)
    X_original = ds['data']['features'].copy()
    X_reg = ds['data']['features'].copy()
    target = ds['data']['original'][['casual','registered','cnt']]
    #X_reg['mnth'] = X_reg['mnth'].astype(float)
    #X_reg['hr'] = X_reg['hr'].astype(float)
    #X_reg['workingday'] = X_reg['workingday'].astype(float)
    X_reg['mnth^2'] = X_reg['mnth']**2
    X_reg['hr^2'] = X_reg['hr']**2
    X_reg['atemp^2'] = X_reg['atemp']**2
    X_reg['hum^2'] = X_reg['hum']**2
    X_reg['windspeed^2'] = X_reg['windspeed']**2
    X_reg = X_reg.drop(['dteday','yr','holiday','weekday','season','temp'],axis=1)
    return X_original, X_reg, target

In [9]:
X_original, X_reg, target = get_data()
#Convertimos a float casi todos los datos enteros, y luego los targets, para representarlos como variables reales en la función de pérdida.
#Dejamos weathersit como entero ya que lo usaremos para estratificar.

In [4]:
X_reg

,mnth,hr,workingday,weathersit,atemp,hum,windspeed,mnth^2,hr^2,atemp^2,hum^2,windspeed^2
0,1.0,0.0,0.0,1,0.2879,0.81,0.0000,1.0,0.0,0.082886,0.6561,0.000000
1,1.0,1.0,0.0,1,0.2727,0.80,0.0000,1.0,1.0,0.074365,0.6400,0.000000
2,1.0,2.0,0.0,1,0.2727,0.80,0.0000,1.0,4.0,0.074365,0.6400,0.000000
3,1.0,3.0,0.0,1,0.2879,0.75,0.0000,1.0,9.0,0.082886,0.5625,0.000000
4,1.0,4.0,0.0,1,0.2879,0.75,0.0000,1.0,16.0,0.082886,0.5625,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
17374,12.0,19.0,1.0,2,0.2576,0.60,0.1642,144.0,361.0,0.066358,0.3600,0.026962
17375,12.0,20.0,1.0,2,0.2576,0.60,0.1642,144.0,400.0,0.066358,0.3600,0.026962
17376,12.0,21.0,1.0,1,0.2576,0.60,0.1642,144.0,441.0,0.066358,0.3600,0.026962
17377,12.0,22.0,1.0,1,0.2727,0.56,0.1343,144.0,484.0,0.074365,0.3136,0.018036
17378,12.0,23.0,1.0,1,0.2727,0.65,0.1343,144.0,529.0,0.074365,0.4225,0.018036

In [17]:
target

       casual  registered  cnt
0           3          13   16
1           8          32   40
2           5          27   32
3           3          10   13
4           0           1    1
...       ...         ...  ...
17374      11         108  119
17375       8          81   89
17376       7          83   90
17377      13          48   61
17378      12          37   49

[17379 rows x 3 columns]

In [4]:
target_float = target.copy()
target_float['casual'] = target_float['casual'].astype(float)
target_float['registered'] = target_float['registered'].astype(float)
target_float['cnt'] = target_float['cnt'].astype(float)
target_float

       casual  registered    cnt
0         3.0        13.0   16.0
1         8.0        32.0   40.0
2         5.0        27.0   32.0
3         3.0        10.0   13.0
4         0.0         1.0    1.0
...       ...         ...    ...
17374    11.0       108.0  119.0
17375     8.0        81.0   89.0
17376     7.0        83.0   90.0
17377    13.0        48.0   61.0
17378    12.0        37.0   49.0

[17379 rows x 3 columns]

Es momento de dividir el dataset y el target en conjuntos de entrenamiento y test. Como tenemos más de 17.000 instancias, creemos que tomar el 10% para test nos dará suficientes casos de test. Por otro lado, dividiremos el conjunto restante en 5 folds. Recordamos que queremos que nuestro modelo aprenda a predecir el uso de bicicletas en un día cualquiera, con la información dada por los features que vimos. Por lo tanto, el conjunto de test y cada fold deberían evitar todo solapamiento de días, para evaluar cómo cada modelo entrenado con ciertos días rinde para otros. Como cada instancia (fila del dataset) corresponde a una fecha diferente, este objetivo se logra sin necesidad de agrupar. Además, no se requiere ninguna estratificación ya que no hay clases, sino un problema de regresión. Por otro lado, hemos visto que el weathersit, un atributo que consideramos de peso, tiene un notable desbalance de clases, y que el valor 4 (evento climático extremo) es estadísticamente insignificante. Queremos que nuestro modelo prediga bien la cantidad de ciclistas para weathersit = 1,2 o 3, así que haremos Stratified Group 5-Fold estratificando sobre este atributo. También cuidaremos las proporciones en el conjunto de test.

In [10]:
X_reg_train, X_reg_test, target_train, target_test = train_test_split(X_reg, target, test_size=0.1, random_state=42,
                                                                      stratify=X_reg['weathersit'])

In [46]:
X_reg_train.groupby(by='weathersit').count()

,mnth,hr,workingday,atemp,hum,windspeed,mnth^2,hr^2,atemp^2,hum^2,windspeed^2
weathersit,,,,,,,,,,,
1,10272,10272,10272,10272,10272,10272,10272,10272,10272,10272,10272
2,4089,4089,4089,4089,4089,4089,4089,4089,4089,4089,4089
3,1277,1277,1277,1277,1277,1277,1277,1277,1277,1277,1277
4,3,3,3,3,3,3,3,3,3,3,3

In [11]:
#Para poder realizar 5 folds, descartaremos las instancias con weathersit = 4 dado que sólo hay 3, lo que no permite dividir en 4 folds.
X_reg_train[X_reg_train['weathersit']==4] #los índices con este valor son el 585, el 8854 y el 9123.
mask = X_reg_train['weathersit'] != 4
X_reg_train = X_reg_train[mask]
target_train = target_train[mask][['casual','registered']]

In [28]:
def regresion_con_regularizacion(train_data,train_target,regularizacion):
    kfold = StratifiedKFold(n_splits=5)
    for alfa in [0.0,1.0,5.0,10.0,20.0,50.0,100.0,1000.0,10000.0]:
        model = Ridge(alpha=alfa,max_iter=10000)
        if regularizacion == 'lasso':
            model = Lasso(alpha=alfa,max_iter=200)
        r2_prom = np.zeros(2)
        for train_idx, val_idx in kfold.split(train_data, train_data['weathersit']):
            X_train_fold, X_val_fold = train_data.iloc[train_idx], train_data.iloc[val_idx]
            target_train_fold, target_val_fold = train_target.iloc[train_idx], train_target.iloc[val_idx]
            model.fit(X_train_fold,target_train_fold)
            pred_val_fold = model.predict(X_val_fold)
            mse = mean_squared_error(target_val_fold,pred_val_fold)
            #print(pred_val_fold-target_val_fold)
            r2_prom += np.array([r2_score(target_val_fold.iloc[:, 0], pred_val_fold[:, 0]),r2_score(target_val_fold.iloc[:, 1], pred_val_fold[:, 1])])
            print('MSE = ',mse)
        r2_prom = r2_prom/5
        print('score con Ridge para alpha = ',alfa,': ',r2_prom)

In [15]:
regresion_con_regularizacion(X_reg_train,target_train,'ridge')

          casual  registered
16553  -5.426029   86.038004
8694  -32.915593  -27.603978
13823  61.381370   89.312671
8897    7.437616   72.437891
10817  -1.764952  -28.494669
...          ...         ...
13598 -42.690580 -303.461555
7863   12.226022 -136.688156
4708    5.748526   60.758806
9226  -22.389083 -387.130407
3819   -2.855620   44.012309

[3128 rows x 2 columns]
MSE =  7641.111549582031
          casual  registered
6462   30.339629   52.369956
6721   25.153142  160.323356
14900 -19.243567  -10.311619
7566    5.101714   87.434370
8051  -17.032859   34.380019
...          ...         ...
600   -23.089509   20.123531
8395   22.157051  161.131001
2604   15.273103   26.483874
8042   -4.656779 -102.040843
7338  -20.743577  -26.138501

[3128 rows x 2 columns]
MSE =  8151.346966437093
           casual  registered
12021  -14.384702   -2.263708
10845  -36.802126  -67.470678
1326    17.874861  123.589954
4315  -100.664601  -47.685752
1476     6.920466    5.305939
...           ...         ...
5742     3.838713 -278.033687
14364    9.230388   21.550221
11787    0.100492 -369.391569
15706 -143.287865 -136.024085
5979   -78.881357  -51.074980

[3128 rows x 2 columns]
MSE =  8080.644641407682
           casual  registered
13968   21.772085   95.541734
252    -24.440859   29.314617
5637    59.957462  115.893392
11650 -157.283210 -112.993888
6231     3.901025   77.752089
...           ...         ...
11967  -12.819560  -11.354163
8147     5.013509  -11.812758
10052   11.621884   -4.658284
10120    1.564200  -14.659122
2262    -5.957111  -86.017157

[3127 rows x 2 columns]
MSE =  7972.712275481625
           casual  registered
15549    6.321368   78.184561
12243    9.990720 -449.053341
8849    15.132691   88.287017
2580    -7.962117   76.214683
13721   -9.835215   14.800947
...           ...         ...
16758  -25.851870    0.291680
3434    -1.368798 -131.526878
14449   15.364563   10.680088
13095 -130.775196  -88.536236
15493  -26.855786 -304.899116

[3127 rows x 2 columns]
MSE =  7809.0485856523355
score con Ridge para alpha =  0.0 :  [0.49791069 0.36553862]
          casual  registered
16553  -5.054609   87.942869
8694  -32.561845  -26.074425
13823  61.396878   89.895892
8897    7.079524   70.345767
10817  -2.066558  -30.881323
...          ...         ...
13598 -42.878880 -302.702768
7863   11.622739 -139.120532
4708    6.342077   63.201293
9226  -22.371391 -387.563971
3819   -3.157597   42.620319

[3128 rows x 2 columns]
MSE =  7647.97620666469
          casual  registered
6462   30.538155   53.421239
6721   24.805440  160.207267
14900 -19.622346  -10.259418
7566    4.770649   86.647070
8051  -17.859168   33.931274
...          ...         ...
600   -22.639699   21.759857
8395   21.788779  159.335440
2604   14.903049   25.361600
8042   -5.348162 -102.027223
7338  -20.747554  -23.521340

[3128 rows x 2 columns]
MSE =  8152.348372348764
           casual  registered
12021  -14.809630   -2.869059
10845  -37.089440  -68.790864
1326    17.044245  121.279037
4315   -96.375244  -32.870201
1476     7.821985   10.272830
...           ...         ...
5742     3.783349 -278.727533
14364    8.997267   21.394385
11787   -0.402950 -371.606111
15706 -143.966707 -137.704597
5979   -78.988652  -51.790536

[3128 rows x 2 columns]
MSE =  8080.8458558472785
           casual  registered
13968   21.845521   95.805486
252    -23.657937   32.128554
5637    60.087901  116.028981
11650 -157.437467 -114.435197
6231     3.659859   78.179669
...           ...         ...
11967  -13.187828  -12.430752
8147     5.968966   -8.754285
10052   11.187579   -6.469446
10120    1.446588  -15.176448
2262    -5.758785  -83.488326

[3127 rows x 2 columns]
MSE =  7973.959894786871
           casual  registered
15549    5.926348   76.058125
12243    9.710413 -450.789543
8849    14.989905   86.788156
2580    -8.005383   74.817904
13721   -9.663958   14.863591
...           ...         ...
16758  -25.714363    0.901282
3434    -1.891015 -132.410939
14449   15.080372    9.913174
13095 -129.933884  -85.437502
15493  -27.427642 -306.355693

[3127 rows x 2 columns]
MSE =  7808.562147995337
score con Ridge para alpha =  1.0 :  [0.49783989 0.36538576]
          casual  registered
16553  -4.141730   92.030313
8694  -31.793672  -22.983869
13823  61.348527   91.006006
8897    6.273557   65.922355
10817  -2.584461  -35.625985
...          ...         ...
13598 -43.373181 -301.217441
7863   10.385299 -144.095957
4708    7.416968   67.978816
9226  -22.247608 -388.427980
3819   -3.748245   39.779463

[3128 rows x 2 columns]
MSE =  7675.351278365574
          casual  registered
6462   31.027823   55.782679
6721   24.071226  160.105967
14900 -20.470155  -10.052609
7566    4.083197   85.092471
8051  -19.831929   32.982616
...          ...         ...
600   -21.681740   25.037835
8395   20.911586  155.495207
2604   14.230030   23.309514
8042   -6.958224 -101.901383
7338  -20.776966  -17.861212

[3128 rows x 2 columns]
MSE =  8168.16859802241
           casual  registered
12021  -15.730126   -3.980046
10845  -37.685861  -71.527977
1326    15.224449  116.553843
4315   -88.205960   -3.975917
1476     9.706366   20.793417
...           ...         ...
5742     3.694286 -280.229454
14364    8.559457   21.329934
11787   -1.296218 -375.945548
15706 -145.448038 -141.038594
5979   -79.234238  -53.323437

[3128 rows x 2 columns]
MSE =  8095.675728664965
           casual  registered
13968   21.961981   96.274895
252    -22.033845   37.866584
5637    60.348343  116.302381
11650 -157.721501 -117.455412
6231     3.109692   79.205405
...           ...         ...
11967  -13.969670  -14.645977
8147     8.041882   -2.392574
10052   10.297505  -10.232006
10120    1.317514  -16.074285
2262    -5.327389  -77.879403

[3127 rows x 2 columns]
MSE =  7990.430215725388
           casual  registered
15549    5.090404   71.515347
12243    9.201881 -454.406143
8849    14.711502   83.530276
2580    -7.841471   72.106909
13721   -9.248994   14.936776
...           ...         ...
16758  -25.401074    2.158677
3434    -3.056411 -134.145629
14449   14.562160    8.464073
13095 -128.298353  -79.266829
15493  -28.561830 -309.176499

[3127 rows x 2 columns]
MSE =  7820.856148126702
score con Ridge para alpha =  5.0 :  [0.49691239 0.36396457]
          casual  registered
16553  -3.472481   94.383680
8694  -31.404205  -21.493263
13823  61.183386   91.430048
8897    5.729117   63.433354
10817  -2.762244  -37.886311
...          ...         ...
13598 -43.719320 -300.558486
7863    9.726200 -146.698553
4708    7.834553   70.208105
9226  -22.132251 -388.883825
3819   -4.049352   38.288088

[3128 rows x 2 columns]
MSE =  7696.06411797937
          casual  registered
6462   31.409449   57.286076
6721   23.702678  160.165859
14900 -20.959528   -9.900247
7566    3.726858   84.330551
8051  -21.146371   32.292921
...          ...         ...
600   -21.184400   26.624262
8395   20.315936  153.322772
2604   14.012663   22.566217
8042   -7.954701 -101.849486
7338  -20.721671  -14.659053

[3128 rows x 2 columns]
MSE =  8183.444811625364
           casual  registered
12021  -16.232777   -4.472697
10845  -38.004241  -72.962818
1326    14.161773  114.047826
4315   -84.457353    9.997002
1476    10.819757   26.641945
...           ...         ...
5742     3.629740 -281.131027
14364    8.415433   21.569990
11787   -1.569364 -377.926503
15706 -146.282302 -142.664848
5979   -79.438088  -54.212481

[3128 rows x 2 columns]
MSE =  8111.062147602353
           casual  registered
13968   21.938599   96.374311
252    -21.201495   40.753075
5637    60.481424  116.513817
11650 -157.893921 -119.076043
6231     2.833471   79.875655
...           ...         ...
11967  -14.399110  -15.829597
8147     9.186999    0.964916
10052    9.847195  -12.210006
10120    1.395319  -16.337879
2262    -5.000101  -74.546888

[3127 rows x 2 columns]
MSE =  8006.603509175744
           casual  registered
15549    4.591352   68.974499
12243    8.987152 -456.311356
8849    14.533440   81.654384
2580    -7.475351   70.977198
13721   -9.010427   14.895279
...           ...         ...
16758  -25.233699    2.765449
3434    -3.735425 -134.973223
14449   14.397894    7.867175
13095 -127.663660  -76.416083
15493  -29.051584 -310.430601

[3127 rows x 2 columns]
MSE =  7834.12088448813
score con Ridge para alpha =  10.0 :  [0.4959649  0.36265687]
          casual  registered
16553  -2.571388   96.769930
8694  -31.161906  -20.483631
13823  60.765202   91.494885
8897    5.021790   60.984882
10817  -2.801120  -39.430940
...          ...         ...
13598 -44.108791 -300.218095
7863    9.131364 -148.956580
4708    7.994064   71.698063
9226  -22.009742 -389.313328
3819   -4.325999   36.968389

[3128 rows x 2 columns]
MSE =  7716.178884506857
          casual  registered
6462   31.970208   59.049792
6721   23.467568  160.353516
14900 -21.402033   -9.774642
7566    3.446459   83.739145
8051  -22.658093   31.221038
...          ...         ...
600   -20.810397   27.764360
8395   19.596686  151.202961
2604   14.082198   22.504278
8042   -8.951984 -101.954593
7338  -20.429302  -11.606101

[3128 rows x 2 columns]
MSE =  8199.682678514575
           casual  registered
12021  -16.646162   -4.819544
10845  -38.290533  -74.179789
1326    13.113304  111.783020
4315   -81.875187   20.714545
1476    12.097486   32.209623
...           ...         ...
5742     3.489840 -282.115045
14364    8.481270   22.206356
11787   -1.462283 -379.123664
15706 -147.042164 -143.901489
5979   -79.791793  -55.124051

[3128 rows x 2 columns]
MSE =  8128.321314771047
           casual  registered
13968   21.733965   96.164782
252    -20.549694   42.995068
5637    60.589891  116.881312
11650 -158.162975 -120.498671
6231     2.716702   80.627969
...           ...         ...
11967  -14.789263  -16.914996
8147    10.183720    3.849643
10052    9.498297  -13.891670
10120    1.713655  -16.211219
2262    -4.456146  -71.112983

[3127 rows x 2 columns]
MSE =  8024.7642504442
           casual  registered
15549    4.016693   66.558997
12243    8.846435 -457.924152
8849    14.263241   79.804559
2580    -6.742997   70.579168
13721   -8.835479   14.723227
...           ...         ...
16758  -25.122701    3.147892
3434    -4.376691 -135.569320
14449   14.468228    7.629473
13095 -127.604012  -74.711015
15493  -29.239544 -311.141450

[3127 rows x 2 columns]
MSE =  7848.5395233407335
score con Ridge para alpha =  20.0 :  [0.49480915 0.36128039]
          casual  registered
16553  -0.731577  100.205748
8694  -31.252042  -20.301791
13823  59.520590   90.736566
8897    3.641769   57.684036
10817  -2.586173  -39.790766
...          ...         ...
13598 -44.712861 -300.604312
7863    8.486083 -151.286162
4708    7.676337   72.038226
9226  -21.843413 -389.840425
3819   -4.681469   35.488277

[3128 rows x 2 columns]
MSE =  7736.681377169738
          casual  registered
6462   33.188305   62.214456
6721   23.567089  160.900341
14900 -21.827642   -9.749797
7566    3.291578   83.325186
8051  -25.071843   28.689502
...          ...         ...
600   -20.595983   28.333033
8395   18.371887  148.424506
2604   14.911605   24.157250
8042  -10.108784 -102.521406
7338  -19.228881   -7.743882

[3128 rows x 2 columns]
MSE =  8218.268206726347
           casual  registered
12021  -16.920973   -5.015808
10845  -38.630532  -75.361692
1326    11.805603  109.203813
4315   -80.882766   28.422974
1476    14.435893   39.396943
...           ...         ...
5742     3.052700 -283.724861
14364    9.162682   24.111156
11787   -0.398486 -378.953421
15706 -147.898814 -144.754816
5979   -80.738933  -56.435975

[3128 rows x 2 columns]
MSE =  8150.334775475686
           casual  registered
13968   20.964184   95.068544
252    -20.068955   44.598905
5637    60.649480  117.872242
11650 -158.907423 -121.942315
6231     3.100180   81.852716
...           ...         ...
11967  -15.235286  -18.277617
8147    11.082579    6.724786
10052    9.275959  -15.514345
10120    2.773669  -15.053076
2262    -3.057067  -66.087771

[3127 rows x 2 columns]
MSE =  8048.307143062992
           casual  registered
15549    2.960389   63.484633
12243    8.778203 -459.440457
8849    13.596687   77.332839
2580    -4.919796   71.845986
13721   -8.816797   14.169295
...           ...         ...
16758  -25.161899    3.045966
3434    -5.105672 -135.806154
14449   15.204888    8.181064
13095 -129.074357  -75.177106
15493  -28.719050 -310.898113

[3127 rows x 2 columns]
MSE =  7864.808827692141
score con Ridge para alpha =  50.0 :  [0.49276014 0.3597467 ]
          casual  registered
16553   1.445621  103.466318
8694  -31.641925  -21.100002
13823  57.852787   89.553704
8897    2.206719   54.897304
10817  -2.249129  -38.603115
...          ...         ...
13598 -45.361000 -301.827129
7863    8.153149 -152.756902
4708    7.087900   71.085508
9226  -21.555660 -390.150563
3819   -4.969406   34.335326

[3128 rows x 2 columns]
MSE =  7751.384305072939
          casual  registered
6462   34.565853   65.800560
6721   24.109936  161.695030
14900 -22.022922   -9.864773
7566    3.421206   83.327536
8051  -27.307449   25.723801
...          ...         ...
600   -20.503907   28.238036
8395   17.248310  146.146672
2604   16.236500   27.204729
8042  -10.680249 -103.110410
7338  -17.298170   -4.357126

[3128 rows x 2 columns]
MSE =  8234.1641253258
           casual  registered
12021  -16.873616   -4.962215
10845  -38.929355  -76.109137
1326    10.923286  107.466589
4315   -82.027818   30.231940
1476    17.089464   45.876652
...           ...         ...
5742     2.465863 -285.468027
14364   10.303260   26.864307
11787    1.206608 -377.617001
15706 -148.657560 -144.947255
5979   -82.064536  -57.626337

[3128 rows x 2 columns]
MSE =  8170.586568272265
           casual  registered
13968   19.888174   93.412725
252    -19.819270   45.107399
5637    60.536712  119.253685
11650 -160.007111 -122.754754
6231     4.010725   83.168816
...           ...         ...
11967  -15.599549  -19.579003
8147    11.404659    8.545420
10052    9.309134  -16.491016
10120    4.294242  -13.162503
2262    -1.278120  -61.113148

[3127 rows x 2 columns]
MSE =  8069.615084708206
           casual  registered
15549    1.738778   60.777635
12243    8.815720 -460.310790
8849    12.800385   75.180002
2580    -2.702004   74.283932
13721   -8.966935   13.412627
...           ...         ...
16758  -25.397510    2.317213
3434    -5.628171 -135.386971
14449   16.471596    9.379124
13095 -131.743100  -77.731634
15493  -27.682840 -309.945341

[3127 rows x 2 columns]
MSE =  7877.957226525854
score con Ridge para alpha =  100.0 :  [0.4896955  0.35859371]

La regresión Ridge no se ve afectada por el parámetro alfa (ni por su ausencia), ya que siempre da lo mismo. Predice mejor el casual que el registered, pero de todos modos un R^2 que da aproximadamente 0.5 es malo. Además, como en 500 iteraciones no se observa una mejora respecto de si hay 200, concluimos que la regresión lineal con los atributos originales y artificiales que definimos no da buenos resultados.

In [ ]:
regresion_con_regularizacion(X_reg_train,target_train,'lasso')

c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.766e+05, tolerance: 3.057e+03
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.805e+06, tolerance: 2.927e+04
  model = cd_fast.enet_coordinate_descent(

MSE =  7778.171260345603

c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.856e+05, tolerance: 3.035e+03
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.698e+06, tolerance: 2.869e+04
  model = cd_fast.enet_coordinate_descent(

MSE =  8294.936459117744

c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.732e+05, tolerance: 2.996e+03
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.683e+06, tolerance: 2.866e+04
  model = cd_fast.enet_coordinate_descent(

MSE =  8234.790611021654

c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.818e+05, tolerance: 2.984e+03
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.800e+06, tolerance: 2.887e+04
  model = cd_fast.enet_coordinate_descent(

MSE =  8128.188275566267

c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.795e+05, tolerance: 2.996e+03
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.849e+06, tolerance: 2.902e+04
  model = cd_fast.enet_coordinate_descent(

MSE =  7916.206886223487
score con Lasso para alpha =  1.0 :  [0.45876974 0.35755159]
MSE =  8208.939294371963
MSE =  8817.265508397079
MSE =  8737.016283091247
MSE =  8623.83403239246
MSE =  8358.76115202595
score con Lasso para alpha =  5.0 :  [0.32845755 0.32974465]
MSE =  8616.591273938706
MSE =  9332.614406055949
MSE =  9198.872819380807
MSE =  9088.591213266038
MSE =  8784.903165406073
score con Lasso para alpha =  10.0 :  [0.21258833 0.30246979]
MSE =  9028.178453544097
MSE =  9802.438264293132
MSE =  9706.585400024565
MSE =  9537.187975569355
MSE =  9158.868816947332
score con Lasso para alpha =  20.0 :  [0.14590649 0.27118523]

Como esperábamos, a la regresión Lasso le va mucho peor, y además empeora cuanto más fuerte hacemos la regularización (y con alfa = 0 ni siquiera converge). El problema es que también le fue mal a la regresión Ridge.

Como en la regresión Ridge las predicciones de registered son mucho peores que las de casual, deducimos que podemos haber dejado de lado información importante sobre los usuarios registrados. Posiblemente a ellos les importen más algunos features que habíamos descartado, como el día de la semana o el holiday. Reentrenaremos las regresiones incorporando estos atributos, sin agregar otros artificiales ya que un usuario registered no necesariamente usará más la bicicleta en fines de semana que durante la semana hábil.

In [16]:
X_reg['weekday'] = X_original['weekday']
X_reg['holiday'] = X_original['holiday']

In [17]:
X_reg_train, X_reg_test, target_train, target_test = train_test_split(X_reg, target, test_size=0.1, random_state=42,
                                                                      stratify=X_reg['weathersit'])
X_reg_train[X_reg_train['weathersit']==4] #los índices con este valor son el 585, el 8854 y el 9123.
mask = X_reg_train['weathersit'] != 4
X_reg_train = X_reg_train[mask]
target_train = target_train[mask][['casual','registered']]

In [18]:
regresion_con_regularizacion(X_reg_train,target_train,'ridge')

          casual  registered
16553  -6.307390   84.278037
8694  -33.500271  -29.010450
13823  64.589347   94.638113
8897    7.682779   72.772418
10817   1.326762  -23.279287
...          ...         ...
13598 -42.935117 -303.844096
7863   11.680668 -137.945054
4708    5.811858   60.847077
9226  -22.128986 -386.784725
3819   -4.305405   41.146100

[3128 rows x 2 columns]
MSE =  7629.7008339857875
          casual  registered
6462   33.735942   56.588430
6721   25.095512  160.283294
14900 -20.266081  -11.734495
7566    5.168055   87.475156
8051  -16.858868   34.440932
...          ...         ...
600   -21.345579   22.570540
8395   22.556560  161.466980
2604   18.702992   30.825738
8042   -5.139442 -102.919710
7338  -22.370867  -28.515495

[3128 rows x 2 columns]
MSE =  8140.443094939485
           casual  registered
12021  -16.562774   -6.169869
10845  -38.940238  -71.353803
1326    16.081630  120.219965
4315  -102.426914  -52.543628
1476     4.824472    0.441871
...           ...         ...
5742     4.836226 -276.195304
14364    7.446007   17.174667
11787    1.633124 -366.262578
15706 -145.150579 -140.733581
5979   -80.539103  -55.425601

[3128 rows x 2 columns]
MSE =  8082.71291138077
           casual  registered
13968   23.407166   97.715944
252    -25.100885   28.366866
5637    58.311784  113.162928
11650 -153.692291 -108.801369
6231     4.624806   78.760358
...           ...         ...
11967  -11.320063   -9.303961
8147     3.743617  -14.277374
10052   10.768547   -5.794655
10120    3.140736  -12.489803
2262    -2.586465  -82.075196

[3127 rows x 2 columns]
MSE =  7961.560598295843
           casual  registered
15549    4.587220   74.759607
12243    9.917435 -449.085283
8849    13.668443   85.234985
2580    -6.495676   79.224288
13721  -11.647316   11.431054
...           ...         ...
16758  -24.937853    1.734330
3434     2.213463 -125.712225
14449   16.120474   12.293570
13095 -139.870547  -94.346876
15493  -25.427318 -302.048900

[3127 rows x 2 columns]
MSE =  7805.1442673583815
score con Ridge para alpha =  0.0 :  [0.50042333 0.36589427]
          casual  registered
16553  -5.930387   86.215744
8694  -33.147093  -27.457868
13823  64.602285   95.173150
8897    7.318650   70.665438
10817   1.012844  -25.736215
...          ...         ...
13598 -43.109289 -303.060727
7863   11.080849 -140.361326
4708    6.404003   63.298046
9226  -22.117483 -387.231699
3819   -4.605117   39.787368

[3128 rows x 2 columns]
MSE =  7636.671151988537
          casual  registered
6462   33.931667   57.591051
6721   24.758976  160.178784
14900 -20.629814  -11.646488
7566    4.841310   86.692228
8051  -17.664971   34.017189
...          ...         ...
600   -20.899141   24.170574
8395   22.181092  159.662530
2604   18.330114   29.649209
8042   -5.808942 -102.865597
7338  -22.347945  -25.831832

[3128 rows x 2 columns]
MSE =  8141.419867853564
           casual  registered
12021  -16.970590   -6.715356
10845  -39.224782  -72.634516
1326    15.261976  117.954343
4315   -98.159956  -37.638105
1476     5.755958    5.523562
...           ...         ...
5742     4.772851 -276.921047
14364    7.229078   17.099319
11787    1.122537 -368.527752
15706 -145.814543 -142.331105
5979   -80.643677  -56.077619

[3128 rows x 2 columns]
MSE =  8082.574653551059
           casual  registered
13968   23.477135   97.950565
252    -24.321751   31.191713
5637    58.439884  113.343485
11650 -153.857229 -110.288479
6231     4.396345   79.189312
...           ...         ...
11967  -11.685513  -10.403893
8147     4.687925  -11.178374
10052   10.334474   -7.593578
10120    3.022600  -13.035846
2262    -2.375919  -79.561943

[3127 rows x 2 columns]
MSE =  7963.005942467593
           casual  registered
15549    4.190109   72.667294
12243    9.628422 -450.839674
8849    13.520316   83.765759
2580    -6.556888   77.759653
13721  -11.475992   11.531705
...           ...         ...
16758  -24.800127    2.333322
3434     1.693677 -126.646748
14449   15.836559   11.502028
13095 -139.065591  -91.419935
15493  -25.996703 -303.542831

[3127 rows x 2 columns]
MSE =  7804.5157523165535
score con Ridge para alpha =  1.0 :  [0.50035694 0.36574427]
          casual  registered
16553  -5.006574   90.369874
8694  -32.386235  -24.326807
13823  64.540041   96.175311
8897    6.496785   66.208761
10817   0.462325  -30.631354
...          ...         ...
13598 -43.570140 -301.519503
7863    9.847402 -145.304125
4708    7.477245   68.092070
9226  -22.011660 -388.129086
3819   -5.193971   37.013898

[3128 rows x 2 columns]
MSE =  7664.35576355576
          casual  registered
6462   34.411574   59.848052
6721   24.050032  160.103079
14900 -21.444657  -11.363294
7566    4.162512   85.146718
8051  -19.595841   33.121054
...          ...         ...
600   -19.949368   27.370167
8395   21.285558  155.802139
2604   17.647462   27.481340
8042   -7.374028 -102.655207
7338  -22.319524  -20.031466

[3128 rows x 2 columns]
MSE =  8157.250509712319
           casual  registered
12021  -17.852425   -7.695557
10845  -39.814758  -75.286174
1326    13.465223  113.327353
4315   -90.044649   -8.565166
1476     7.698365   16.283588
...           ...         ...
5742     4.664789 -278.493038
14364    6.816941   17.200937
11787    0.219058 -372.968751
15706 -147.272691 -145.491282
5979   -80.897192  -57.485594

[3128 rows x 2 columns]
MSE =  8096.824231848452
           casual  registered
13968   23.587884   98.357868
252    -22.709573   36.949547
5637    58.681771  113.704630
11650 -154.170584 -113.412196
6231     3.879772   80.223047
...           ...         ...
11967  -12.456077  -12.665338
8147     6.718764   -4.742580
10052    9.443681  -11.329920
10120    2.897426  -13.991948
2262    -1.916074  -73.984534

[3127 rows x 2 columns]
MSE =  7979.904887818343
           casual  registered
15549    3.344731   68.194602
12243    9.100125 -454.495519
8849    13.223169   80.565280
2580    -6.429002   74.905914
13721  -11.065577   11.681155
...           ...         ...
16758  -24.488643    3.565393
3434     0.531313 -128.489749
14449   15.322435   10.004032
13095 -137.427230  -85.554589
15493  -27.119090 -306.435425

[3127 rows x 2 columns]
MSE =  7816.619154251191
score con Ridge para alpha =  5.0 :  [0.49944681 0.36432127]
          casual  registered
16553  -4.330510   92.759070
8694  -32.005660  -22.820111
13823  64.352964   96.531099
8897    5.939750   63.698612
10817   0.255804  -32.978063
...          ...         ...
13598 -43.895384 -300.827533
7863    9.186674 -147.891644
4708    7.894392   70.328749
9226  -21.910537 -388.607342
3819   -5.495487   35.557155

[3128 rows x 2 columns]
MSE =  7685.267888114599
          casual  registered
6462   34.780252   61.292854
6721   23.696141  160.177267
14900 -21.915622  -11.169832
7566    3.809703   84.389016
8051  -20.892171   32.456558
...          ...         ...
600   -19.457478   28.913698
8395   20.674570  153.615487
2604   17.417301   26.673247
8042   -8.351100 -102.561743
7338  -22.233584  -16.755408

[3128 rows x 2 columns]
MSE =  8172.564739531978
           casual  registered
12021  -18.331072   -8.114242
10845  -40.127118  -76.672022
1326    12.414132  110.874456
4315   -86.336771    5.493698
1476     8.834931   22.257151
...           ...         ...
5742     4.587861 -279.434759
14364    6.675168   17.524566
11787   -0.054152 -374.998772
15706 -148.106632 -147.028081
5979   -81.121599  -58.317336

[3128 rows x 2 columns]
MSE =  8111.964196116494
           casual  registered
13968   23.562766   98.423637
252    -21.887254   39.843854
5637    58.788414  113.954227
11650 -154.369123 -115.095924
6231     3.626742   80.901230
...           ...         ...
11967  -12.874410  -13.870710
8147     7.819904   -1.357656
10052    8.992105  -13.293599
10120    2.982792  -14.283757
2262    -1.576696  -70.670405

[3127 rows x 2 columns]
MSE =  7996.310197978222
           casual  registered
15549    2.836758   65.689807
12243    8.874760 -456.421807
8849    13.028579   78.715883
2580    -6.077935   73.702746
13721  -10.831674   11.678462
...           ...         ...
16758  -24.325153    4.156215
3434    -0.155189 -129.381631
14449   15.163747    9.383414
13095 -136.670207  -82.794148
15493  -27.596820 -307.722091

[3127 rows x 2 columns]
MSE =  7829.829705796848
score con Ridge para alpha =  10.0 :  [0.49851426 0.36300891]
          casual  registered
16553  -3.419894   95.179516
8694  -31.776297  -21.801276
13823  63.887306   96.517552
8897    5.214831   61.225834
10817   0.170101  -34.608902
...          ...         ...
13598 -44.263836 -300.456010
7863    8.584625 -150.141167
4708    8.052826   71.822228
9226  -21.806120 -389.061338
3819   -5.772077   34.267010

[3128 rows x 2 columns]
MSE =  7705.572033676668
          casual  registered
6462   35.313351   63.001473
6721   23.474231  160.377111
14900 -22.342078  -11.009819
7566    3.529843   83.799623
8051  -22.399558   31.398358
...          ...         ...
600   -19.089498   30.017133
8395   19.931253  151.476114
2604   17.459327   26.550009
8042   -9.343416 -102.640589
7338  -21.917789  -13.642945

[3128 rows x 2 columns]
MSE =  8188.861493543893
           casual  registered
12021  -18.718289   -8.393177
10845  -40.401848  -77.841113
1326    11.373578  108.652919
4315   -83.813102   16.270877
1476    10.117152   27.925912
...           ...         ...
5742     4.434274 -280.456312
14364    6.722229   18.222319
11787    0.061119 -376.230051
15706 -148.888985 -148.196779
5979   -81.519541  -59.194106

[3128 rows x 2 columns]
MSE =  8129.044215185409
           casual  registered
13968   23.358387   98.185528
252    -21.248817   42.089002
5637    58.846829  114.339260
11650 -154.680110 -116.583836
6231     3.534676   81.663417
...           ...         ...
11967  -13.248256  -14.970247
8147     8.744508    1.531816
10052    8.641266  -14.962855
10120    3.315964  -14.175867
2262    -1.035380  -67.258149

[3127 rows x 2 columns]
MSE =  8014.677550813742
           casual  registered
15549    2.250948   63.304023
12243    8.726983 -458.051268
8849    12.736829   76.884256
2580    -5.349030   73.249972
13721  -10.660111   11.539476
...           ...         ...
16758  -24.222488    4.522621
3434    -0.825912 -130.047519
14449   15.243358    9.128124
13095 -136.275795  -81.042433
15493  -27.767936 -308.453936

[3127 rows x 2 columns]
MSE =  7844.226597434356
score con Ridge para alpha =  20.0 :  [0.49736939 0.36162676]
          casual  registered
16553  -1.559415   98.659695
8694  -31.889995  -21.618463
13823  62.511765   95.629953
8897    3.799877   57.884820
10817   0.273497  -35.083760
...          ...         ...
13598 -44.841676 -300.807646
7863    7.916664 -152.475945
4708    7.730695   72.156830
9226  -21.671045 -389.623212
3819   -6.123192   32.815810

[3128 rows x 2 columns]
MSE =  7726.341762897162
          casual  registered
6462   36.452245   66.102341
6721   23.586357  160.933891
14900 -22.753308  -10.957220
7566    3.367651   83.382658
8051  -24.845075   28.854346
...          ...         ...
600   -18.883113   30.555657
8395   18.651473  148.657285
2604   18.209956   28.130140
8042  -10.533655 -103.213790
7338  -20.708213   -9.740637

[3128 rows x 2 columns]
MSE =  8207.589115739562
           casual  registered
12021  -18.952393   -8.516694
10845  -40.710369  -78.962135
1326    10.067069  106.102971
4315   -82.946366   23.996467
1476    12.410908   35.186790
...           ...         ...
5742     3.977032 -282.107318
14364    7.322918   20.151343
11787    1.154628 -376.069047
15706 -149.836701 -149.016112
5979   -82.584413  -60.513483

[3128 rows x 2 columns]
MSE =  8150.963010587403
           casual  registered
13968   22.595392   97.067052
252    -20.793168   43.686015
5637    58.779147  115.300292
11650 -155.521738 -118.115329
6231     3.950276   82.903148
...           ...         ...
11967  -13.660657  -16.331814
8147     9.475488    4.356851
10052    8.414547  -16.574959
10120    4.413177  -13.017782
2262     0.313653  -62.271695

[3127 rows x 2 columns]
MSE =  8038.484587073224
           casual  registered
15549    1.178134   60.255277
12243    8.660944 -459.577175
8849    12.033412   74.419056
2580    -3.499649   74.493861
13721  -10.637443   11.018520
...           ...         ...
16758  -24.283814    4.402502
3434    -1.658505 -130.393593
14449   15.999781    9.669712
13095 -136.725755  -81.118519
15493  -27.217120 -308.212566

[3127 rows x 2 columns]
MSE =  7860.560217918087
score con Ridge para alpha =  50.0 :  [0.49528555 0.36008546]
          casual  registered
16553   0.639338  101.954506
8694  -32.303626  -22.423775
13823  60.678765   94.326951
8897    2.327981   55.059191
10817   0.474244  -33.986073
...          ...         ...
13598 -45.469440 -302.006574
7863    7.554076 -153.966063
4708    7.136606   71.191270
9226  -21.414546 -389.963163
3819   -6.403508   31.675642

[3128 rows x 2 columns]
MSE =  7741.398415309996
          casual  registered
6462   37.723538   69.649024
6721   24.135287  161.731709
14900 -22.942762  -11.065660
7566    3.484539   83.378505
8051  -27.136663   25.854828
...          ...         ...
600   -18.795357   30.456655
8395   17.463847  146.335067
2604   19.429898   31.129534
8042  -11.167440 -103.844193
7338  -18.793091   -6.358877

[3128 rows x 2 columns]
MSE =  8223.715276489855
           casual  registered
12021  -18.865149   -8.420215
10845  -40.969105  -79.664201
1326     9.179136  104.362800
4315   -84.235144   25.770000
1476    14.979740   41.672169
...           ...         ...
5742     3.373439 -283.874320
14364    8.344274   22.870544
11787    2.798323 -374.708049
15706 -150.726894 -149.231042
5979   -84.059583  -61.757520

[3128 rows x 2 columns]
MSE =  8171.327726303517
           casual  registered
13968   21.535702   95.413146
252    -20.571886   44.177429
5637    58.503293  116.605459
11650 -156.736378 -118.993127
6231     4.886085   84.234482
...           ...         ...
11967  -13.984517  -17.610304
8147     9.587968    6.081183
10052    8.440409  -17.550635
10120    5.980183  -11.102249
2262     2.008059  -57.331690

[3127 rows x 2 columns]
MSE =  8060.088975455423
           casual  registered
15549   -0.057188   57.556891
12243    8.710804 -460.445080
8849    11.200596   72.255076
2580    -1.235692   76.956704
13721  -10.775848   10.277603
...           ...         ...
16758  -24.546738    3.666398
3434    -2.324975 -130.072677
14449   17.287742   10.870493
13095 -138.016635  -83.104977
15493  -26.150851 -307.236911

[3127 rows x 2 columns]
MSE =  7873.948206025645
score con Ridge para alpha =  100.0 :  [0.49209343 0.35892435]

Los resultados para Ridge son aproximadamente iguales, por lo que estos nuevos atributos no parecen tener mucha incidencia. No obstante, recordamos una observación que habíamos hecho en el archivo de exploración: hay muchos más usuarios registered en 2012 (y algunos más de tipo casual) que en 2011. Aunque el objetivo sigue siendo lograr predicciones independientes del año, podemos volver a correr estos modelos incorporando el año para ver si los resultados mejoran artificialmente. Otra alternativa es, ya que queremos predecir uso de bicicletas en el futuro, descartar directamente el año anterior ya que la realidad del último año debería ser más cercana a la del próximo. A continuación procedemos con estas dos alternativas.

In [29]:
X_reg['weekday'] = X_original['weekday']
X_reg['holiday'] = X_original['holiday']
X_reg['yr'] = X_original['yr']

In [30]:
X_reg_train, X_reg_test, target_train, target_test = train_test_split(X_reg, target, test_size=0.1, random_state=42,
                                                                      stratify=X_reg['weathersit'])
X_reg_train[X_reg_train['weathersit']==4] #los índices con este valor son el 585, el 8854 y el 9123.
mask = X_reg_train['weathersit'] != 4
X_reg_train = X_reg_train[mask]
target_train = target_train[mask][['casual','registered']]

In [21]:
X_reg

,mnth,hr,workingday,weathersit,atemp,hum,windspeed,mnth^2,hr^2,atemp^2,hum^2,windspeed^2,weekday,holiday,yr
0,1,0,0,1,0.2879,0.81,0.0000,1,0,0.082886,0.6561,0.000000,6,0,0
1,1,1,0,1,0.2727,0.80,0.0000,1,1,0.074365,0.6400,0.000000,6,0,0
2,1,2,0,1,0.2727,0.80,0.0000,1,4,0.074365,0.6400,0.000000,6,0,0
3,1,3,0,1,0.2879,0.75,0.0000,1,9,0.082886,0.5625,0.000000,6,0,0
4,1,4,0,1,0.2879,0.75,0.0000,1,16,0.082886,0.5625,0.000000,6,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17374,12,19,1,2,0.2576,0.60,0.1642,144,361,0.066358,0.3600,0.026962,1,0,1
17375,12,20,1,2,0.2576,0.60,0.1642,144,400,0.066358,0.3600,0.026962,1,0,1
17376,12,21,1,1,0.2576,0.60,0.1642,144,441,0.066358,0.3600,0.026962,1,0,1
17377,12,22,1,1,0.2727,0.56,0.1343,144,484,0.074365,0.3136,0.018036,1,0,1
17378,12,23,1,1,0.2727,0.65,0.1343,144,529,0.074365,0.4225,0.018036,1,0,1

In [31]:
regresion_con_regularizacion(X_reg_train,target_train,'ridge')

MSE =  9055.192815258388
MSE =  10080.431763707851
MSE =  10404.500663000437
MSE =  10563.016203803589
MSE =  9924.834450219736
score con Ridge para alpha =  0.0 :  [0.53592205 0.39913434]
MSE =  9069.683562350949
MSE =  10091.951745655693
MSE =  10401.955438275123
MSE =  10585.511729599848
MSE =  9923.33612755194
score con Ridge para alpha =  1.0 :  [0.5353743  0.39862082]
MSE =  9119.35489243638
MSE =  10137.773465042872
MSE =  10437.254607658831
MSE =  10648.272468809764
MSE =  9954.160614026934
score con Ridge para alpha =  5.0 :  [0.5323971  0.39602861]
MSE =  9144.963162818347
MSE =  10163.477018846781
MSE =  10458.92306134166
MSE =  10682.074874129457
MSE =  9971.588532769236
score con Ridge para alpha =  10.0 :  [0.53050178 0.39462249]
MSE =  9166.075334471794
MSE =  10187.277369088493
MSE =  10477.242105288355
MSE =  10714.739585767253
MSE =  9983.526332605381
score con Ridge para alpha =  20.0 :  [0.52831248 0.39346691]
MSE =  9192.663136965784
MSE =  10222.87509815822
MSE =  10503.358463484397
MSE =  10765.715630939163
MSE =  9994.703111280276
score con Ridge para alpha =  50.0 :  [0.52314537 0.39209338]
MSE =  9221.692548420384
MSE =  10263.8779436958
MSE =  10539.047613855895
MSE =  10822.894554044931
MSE =  10010.238094904442
score con Ridge para alpha =  100.0 :  [0.51507122 0.39067202]
MSE =  9435.632326301087
MSE =  10570.212482442192
MSE =  10891.148943384753
MSE =  11248.529287921743
MSE =  10187.598116734374
score con Ridge para alpha =  1000.0 :  [0.45007667 0.3787186 ]
MSE =  10441.385429835245
MSE =  11805.118937971665
MSE =  12301.674988960116
MSE =  12703.551084400755
MSE =  11209.610619380246
score con Ridge para alpha =  10000.0 :  [0.29779267 0.31578614]

Notamos que incorporar el año sí mejoró el R^2 para registered, pero no tanto como esperábamos. El siguiente paso es eliminar los registros del año 2011 para ver cuáles son los resultados con ese procedimiento.

In [32]:
X_original, X_reg, target = get_data()
X_reg['weekday'] = X_original['weekday']
X_reg['holiday'] = X_original['holiday']
X_reg['yr'] = X_original['yr']

mascara_clima = X_reg['weathersit'] != 4
X_reg = X_reg[mascara_clima]
target = target[mascara_clima][['casual','registered']]

mascara_2012 = X_reg['yr'] == 1
X_reg = X_reg[mascara_2012]
target = target[mascara_2012]

X_reg = X_reg.drop(['yr'],axis=1)

X_reg_train, X_reg_test, target_train, target_test = train_test_split(X_reg, target, test_size=0.1, random_state=42,
                                                                      stratify=X_reg['weathersit'])

In [33]:
regresion_con_regularizacion(X_reg_train,target_train,'ridge')

MSE =  9055.192815258375
MSE =  10080.43176370785
MSE =  10404.500663000417
MSE =  10563.016203803576
MSE =  9924.834450219725
score con Ridge para alpha =  0.0 :  [0.53592205 0.39913434]
MSE =  9069.683562350949
MSE =  10091.951745655693
MSE =  10401.955438275121
MSE =  10585.511729599848
MSE =  9923.33612755194
score con Ridge para alpha =  1.0 :  [0.5353743  0.39862082]
MSE =  9119.354892436379
MSE =  10137.773465042872
MSE =  10437.254607658831
MSE =  10648.272468809764
MSE =  9954.160614026932
score con Ridge para alpha =  5.0 :  [0.5323971  0.39602861]
MSE =  9144.963162818347
MSE =  10163.47701884678
MSE =  10458.92306134166
MSE =  10682.074874129456
MSE =  9971.588532769236
score con Ridge para alpha =  10.0 :  [0.53050178 0.39462249]
MSE =  9166.075334471794
MSE =  10187.277369088491
MSE =  10477.242105288355
MSE =  10714.739585767253
MSE =  9983.526332605381
score con Ridge para alpha =  20.0 :  [0.52831248 0.39346691]
MSE =  9192.663136965784
MSE =  10222.87509815822
MSE =  10503.358463484397
MSE =  10765.715630939163
MSE =  9994.703111280276
score con Ridge para alpha =  50.0 :  [0.52314537 0.39209338]
MSE =  9221.692548420384
MSE =  10263.8779436958
MSE =  10539.047613855895
MSE =  10822.894554044931
MSE =  10010.238094904442
score con Ridge para alpha =  100.0 :  [0.51507122 0.39067202]
MSE =  9435.632326301087
MSE =  10570.212482442192
MSE =  10891.148943384753
MSE =  11248.529287921743
MSE =  10187.598116734374
score con Ridge para alpha =  1000.0 :  [0.45007667 0.3787186 ]
MSE =  10441.385429835245
MSE =  11805.118937971665
MSE =  12301.674988960116
MSE =  12703.551084400755
MSE =  11209.610619380246
score con Ridge para alpha =  10000.0 :  [0.29779267 0.31578614]

In [18]:
regresion_con_regularizacion(X_reg_train,target_train,'lasso')

c:\Users\Lenny\Python39\lib\site-packages\sklearn\base.py:1474: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.745e+06, tolerance: 2.056e+03 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.934e+07, tolerance: 1.983e+04 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\base.py:1474: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.758e+06, tolerance: 2.073e+03 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(

MSE =  9055.490664039522
MSE =  10080.613054664567

c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.772e+07, tolerance: 1.933e+04 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\base.py:1474: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.673e+06, tolerance: 2.014e+03 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.732e+07, tolerance: 1.910e+04 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\base.py:1474: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)

MSE =  10403.517691088713
MSE =  10563.256352804046

c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.655e+06, tolerance: 2.017e+03 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.709e+07, tolerance: 1.899e+04 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\base.py:1474: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.752e+06, tolerance: 2.058e+03 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.799e+07, tolerance: 1.971e+04 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(

MSE =  9924.229267333274
score con Ridge para alpha =  0.0 :  [0.53593663 0.39914376]
MSE =  9231.0594917424

c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.173e+04, tolerance: 2.056e+03
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.089e+06, tolerance: 1.983e+04
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.031e+05, tolerance: 2.073e+03
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.110e+06, tolerance: 1.933e+04
  model = cd_fast.enet_coordinate_descent(

MSE =  10283.495891950159
MSE =  10570.791835508693
MSE =  10854.152236462895

c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.616e+04, tolerance: 2.014e+03
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.598e+05, tolerance: 1.910e+04
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.011e+04, tolerance: 2.017e+03
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.126e+05, tolerance: 1.899e+04
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.653e+04, tolerance: 2.058e+03
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.282e+05, tolerance: 1.971e+04
  model = cd_fast.enet_coordinate_descent(

MSE =  10008.848797062305
score con Ridge para alpha =  1.0 :  [0.49800697 0.39135065]
MSE =  9664.169572781278
MSE =  10805.731665718835
MSE =  11118.671848693437
MSE =  11506.951477479954
MSE =  10396.118128740636
score con Ridge para alpha =  5.0 :  [0.37217623 0.37191366]
MSE =  10110.919494437894
MSE =  11354.543817027878
MSE =  11674.958571631412
MSE =  12165.350858470649
MSE =  10820.867058500326
score con Ridge para alpha =  10.0 :  [0.25996137 0.34979195]
MSE =  10637.575839733667
MSE =  11955.180692930677
MSE =  12382.931497120955
MSE =  12907.56352132202
MSE =  11358.028928031015
score con Ridge para alpha =  20.0 :  [0.18801694 0.31716776]
MSE =  11361.958903028506
MSE =  12797.908533362859
MSE =  13330.243753107074
MSE =  13748.921435520342
MSE =  12131.45867228421
score con Ridge para alpha =  50.0 :  [0.04385347 0.27884798]
MSE =  12457.631617462199
MSE =  14116.379949255082
MSE =  14731.221327988866
MSE =  15022.46461988535
MSE =  13358.849841560024
score con Ridge para alpha =  100.0 :  [0.0438107  0.19689862]

Habiendo probado estas alternativas, vemos que la regresión lineal agregando variables cuadráticas no funciona, sobre todo teniendo en cuenta los MSE obtenidos, que son altísimos. Probaremos modelos de regresión con ensambles, comenzando por un RandomForestRegressor. Como la propia arquitectura de este modelo presenta aleatorización para prevenir el sobreajuste, usaremos todos los atributos de la base de datos excepto el instante (que funciona como id) y la fecha. Como incluimos el año, lo cual no es ideal, luego haremos lo mismo sólo para 2012.

In [46]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import HistGradientBoostingRegressor

In [37]:
X_original

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed
0,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000
1,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000
2,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000
3,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000
4,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17374,2012-12-31,1,1,12,19,0,1,1,2,0.26,0.2576,0.60,0.1642
17375,2012-12-31,1,1,12,20,0,1,1,2,0.26,0.2576,0.60,0.1642
17376,2012-12-31,1,1,12,21,0,1,1,1,0.26,0.2576,0.60,0.1642
17377,2012-12-31,1,1,12,22,0,1,1,1,0.26,0.2727,0.56,0.1343
17378,2012-12-31,1,1,12,23,0,1,1,1,0.26,0.2727,0.65,0.1343

In [54]:
def regresion_random_forest(lista_max_depth,lista_min_samples_split,lista_max_features,train_data,train_target):
    kfold = StratifiedKFold(n_splits=5)
    """
    for alfa in [0.0,1.0,5.0,10.0,20.0,50.0,100.0,1000.0,10000.0]:
        model = Ridge(alpha=alfa,max_iter=10000)
        if regularizacion == 'lasso':
            model = Lasso(alpha=alfa,max_iter=200)
        r2_prom = np.zeros(2)
        for train_idx, val_idx in kfold.split(train_data, train_data['weathersit']):
            X_train_fold, X_val_fold = train_data.iloc[train_idx], train_data.iloc[val_idx]
            target_train_fold, target_val_fold = train_target.iloc[train_idx], train_target.iloc[val_idx]
            model.fit(X_train_fold,target_train_fold)
            pred_val_fold = model.predict(X_val_fold)
            mse = mean_squared_error(target_val_fold,pred_val_fold)
            #print(pred_val_fold-target_val_fold)
            r2_prom += np.array([r2_score(target_val_fold.iloc[:, 0], pred_val_fold[:, 0]),r2_score(target_val_fold.iloc[:, 1], pred_val_fold[:, 1])])
            print('MSE = ',mse)
        r2_prom = r2_prom/5
        print('score con Ridge para alpha = ',alfa,': ',r2_prom) 
    """
    for prof_max in lista_max_depth:
        for min_split in lista_min_samples_split:
            for max_feat in lista_max_features:
                model_1 = RandomForestRegressor(criterion='squared_error',max_depth=prof_max,min_samples_split=min_split,
                                              max_features=max_feat,random_state=42)
                model_2 = RandomForestRegressor(criterion='squared_error',max_depth=prof_max,min_samples_split=min_split,
                                                              max_features=max_feat,random_state=42)
                                
                r2_prom = np.zeros(2)
                for train_idx, val_idx in kfold.split(train_data, train_data['weathersit']):
                    X_train_fold, X_val_fold = train_data.iloc[train_idx], train_data.iloc[val_idx]
                    target_train_fold, target_val_fold = train_target.iloc[train_idx], train_target.iloc[val_idx]
                    model_1.fit(X_train_fold,target_train_fold.iloc[:,0])
                    pred_val_fold_1 = model_1.predict(X_val_fold)
                    model_2.fit(X_train_fold,target_train_fold.iloc[:,1])
                    pred_val_fold_2 = model_2.predict(X_val_fold)
                    r2_prom += np.array([r2_score(target_val_fold.iloc[:, 0], pred_val_fold_1),r2_score(target_val_fold.iloc[:, 1], pred_val_fold_2)])
                r2_prom = r2_prom/5
                print(prof_max,min_split,max_feat,'r2 promedio = ',r2_prom)

In [55]:
X_original, X_reg, target = get_data()
mascara_clima = X_original['weathersit'] != 4
X_original = X_original[mascara_clima]
target = target[mascara_clima]
X_reg = X_original.drop(['dteday'],axis=1)
X_reg_train, X_reg_test, target_train, target_test = train_test_split(X_reg, target, test_size=0.1, random_state=42,
                                                                      stratify=X_reg['weathersit'])
lista_max_depth = [3,5,7,None]
lista_min_samples_split = [2,5,25,50]
lista_max_features = ['sqrt',None]
regresion_random_forest(lista_max_depth,lista_min_samples_split,lista_max_features,X_reg_train,target_train)

3 2 sqrt r2 promedio =  [0.53329641 0.39905652]
3 2 None r2 promedio =  [0.58789582 0.45489322]
3 5 sqrt r2 promedio =  [0.53329641 0.39905652]
3 5 None r2 promedio =  [0.58789582 0.45489322]
3 25 sqrt r2 promedio =  [0.53329641 0.39905652]
3 25 None r2 promedio =  [0.58789582 0.45489322]
3 50 sqrt r2 promedio =  [0.53329153 0.39905652]
3 50 None r2 promedio =  [0.58789582 0.45489322]
5 2 sqrt r2 promedio =  [0.69444956 0.52322499]
5 2 None r2 promedio =  [0.77247277 0.62429365]
5 5 sqrt r2 promedio =  [0.6936929  0.52335205]
5 5 None r2 promedio =  [0.77247277 0.62429371]
5 25 sqrt r2 promedio =  [0.69219864 0.52345259]
5 25 None r2 promedio =  [0.77245777 0.62429341]
5 50 sqrt r2 promedio =  [0.69146845 0.52295853]
5 50 None r2 promedio =  [0.77240197 0.62429408]
7 2 sqrt r2 promedio =  [0.78456107 0.64357441]
7 2 None r2 promedio =  [0.83663788 0.84992678]
7 5 sqrt r2 promedio =  [0.78945583 0.64496131]
7 5 None r2 promedio =  [0.83662001 0.8499208 ]
7 25 sqrt r2 promedio =  [0.78197274 0.64488553]
7 25 None r2 promedio =  [0.83617506 0.84985969]
7 50 sqrt r2 promedio =  [0.77897516 0.63979021]
7 50 None r2 promedio =  [0.83541447 0.84955008]
None 2 sqrt r2 promedio =  [0.90386224 0.89268951]
None 2 None r2 promedio =  [0.90909769 0.94439058]
None 5 sqrt r2 promedio =  [0.89964097 0.88359213]
None 5 None r2 promedio =  [0.90749117 0.94426587]
None 25 sqrt r2 promedio =  [0.86543978 0.83501829]
None 25 None r2 promedio =  [0.89307388 0.93704899]
None 50 sqrt r2 promedio =  [0.84181363 0.79951175]
None 50 None r2 promedio =  [0.8788619  0.92702087]

In [49]:
def regresion_hist_boosting(lista_max_depth,lista_min_samples_leaf,lista_max_features,train_data,train_target):
    kfold = StratifiedKFold(n_splits=5)
    """
    for alfa in [0.0,1.0,5.0,10.0,20.0,50.0,100.0,1000.0,10000.0]:
        model = Ridge(alpha=alfa,max_iter=10000)
        if regularizacion == 'lasso':
            model = Lasso(alpha=alfa,max_iter=200)
        r2_prom = np.zeros(2)
        for train_idx, val_idx in kfold.split(train_data, train_data['weathersit']):
            X_train_fold, X_val_fold = train_data.iloc[train_idx], train_data.iloc[val_idx]
            target_train_fold, target_val_fold = train_target.iloc[train_idx], train_target.iloc[val_idx]
            model.fit(X_train_fold,target_train_fold)
            pred_val_fold = model.predict(X_val_fold)
            mse = mean_squared_error(target_val_fold,pred_val_fold)
            #print(pred_val_fold-target_val_fold)
            r2_prom += np.array([r2_score(target_val_fold.iloc[:, 0], pred_val_fold[:, 0]),r2_score(target_val_fold.iloc[:, 1], pred_val_fold[:, 1])])
            print('MSE = ',mse)
        r2_prom = r2_prom/5
        print('score con Ridge para alpha = ',alfa,': ',r2_prom) 
    """
    for prof_max in lista_max_depth:
        for min_leaf in lista_min_samples_leaf:
            for max_feat in lista_max_features:
                model_1 = HistGradientBoostingRegressor(loss='squared_error',max_depth=prof_max,min_samples_leaf=min_leaf,
                                              max_features=max_feat,random_state=42)
                model_2 = HistGradientBoostingRegressor(loss='squared_error',max_depth=prof_max,min_samples_leaf=min_leaf,
                                                              max_features=max_feat,random_state=42)
                r2_prom = np.zeros(2)
                for train_idx, val_idx in kfold.split(train_data, train_data['weathersit']):
                    X_train_fold, X_val_fold = train_data.iloc[train_idx], train_data.iloc[val_idx]
                    target_train_fold, target_val_fold = train_target.iloc[train_idx], train_target.iloc[val_idx]
                    model_1.fit(X_train_fold,target_train_fold.iloc[:,0])
                    model_2.fit(X_train_fold,target_train_fold.iloc[:,1])
                    pred_val_fold_1 = model_1.predict(X_val_fold)
                    pred_val_fold_2 = model_2.predict(X_val_fold)
                    r2_prom += np.array([r2_score(target_val_fold.iloc[:, 0], pred_val_fold_1),r2_score(target_val_fold.iloc[:, 1], pred_val_fold_2)])
                r2_prom = r2_prom/5
                print(prof_max,min_leaf,max_feat,'r2 promedio = ',r2_prom)

In [57]:
X_original, X_reg, target = get_data()
mascara_clima = X_original['weathersit'] != 4
X_original = X_original[mascara_clima]
target = target[mascara_clima]
X_reg = X_original.drop(['dteday'],axis=1)
X_reg_train, X_reg_test, target_train, target_test = train_test_split(X_reg, target, test_size=0.1, random_state=42,
                                                                      stratify=X_reg['weathersit'])
lista_max_depth = [3,5,7,None]
lista_min_samples_leaf = [1,5,25,50]
lista_max_features = [0.25,0.5,0.75,1.0]
regresion_hist_boosting(lista_max_depth,lista_min_samples_leaf,lista_max_features,X_reg_train,target_train)

3 1 0.25 r2 promedio =  [0.80726725 0.75332276]
3 1 0.5 r2 promedio =  [0.82549591 0.84356925]
3 1 0.75 r2 promedio =  [0.82482373 0.84317821]
3 1 1.0 r2 promedio =  [0.82618613 0.8556242 ]
3 5 0.25 r2 promedio =  [0.80461726 0.75447179]
3 5 0.5 r2 promedio =  [0.82491951 0.84130427]
3 5 0.75 r2 promedio =  [0.8251372  0.84651456]
3 5 1.0 r2 promedio =  [0.82600858 0.85661067]
3 25 0.25 r2 promedio =  [0.80748336 0.74343426]
3 25 0.5 r2 promedio =  [0.82517226 0.84738976]
3 25 0.75 r2 promedio =  [0.82469699 0.84549799]
3 25 1.0 r2 promedio =  [0.82554084 0.85745944]
3 50 0.25 r2 promedio =  [0.80724498 0.74283777]
3 50 0.5 r2 promedio =  [0.82299898 0.84004979]
3 50 0.75 r2 promedio =  [0.82486471 0.83601426]
3 50 1.0 r2 promedio =  [0.82620751 0.85653417]
5 1 0.25 r2 promedio =  [0.88179673 0.8791599 ]
5 1 0.5 r2 promedio =  [0.89235188 0.9316863 ]
5 1 0.75 r2 promedio =  [0.89397742 0.93432361]
5 1 1.0 r2 promedio =  [0.89301776 0.93523803]
5 5 0.25 r2 promedio =  [0.88225704 0.878172  ]
5 5 0.5 r2 promedio =  [0.89116808 0.93236247]
5 5 0.75 r2 promedio =  [0.89208886 0.93446386]
5 5 1.0 r2 promedio =  [0.892852   0.93493382]
5 25 0.25 r2 promedio =  [0.87969397 0.89145089]
5 25 0.5 r2 promedio =  [0.88679969 0.92928369]
5 25 0.75 r2 promedio =  [0.88858411 0.93398308]
5 25 1.0 r2 promedio =  [0.8893596  0.93396221]
5 50 0.25 r2 promedio =  [0.87564717 0.88189909]
5 50 0.5 r2 promedio =  [0.88349514 0.92878457]
5 50 0.75 r2 promedio =  [0.88551863 0.9322091 ]
5 50 1.0 r2 promedio =  [0.88605743 0.93317391]
7 1 0.25 r2 promedio =  [0.89986361 0.91881302]
7 1 0.5 r2 promedio =  [0.90754575 0.94336175]
7 1 0.75 r2 promedio =  [0.90758833 0.94508429]
7 1 1.0 r2 promedio =  [0.90882061 0.94589884]
7 5 0.25 r2 promedio =  [0.90076385 0.92021277]
7 5 0.5 r2 promedio =  [0.90710775 0.9439392 ]
7 5 0.75 r2 promedio =  [0.90807383 0.94625767]
7 5 1.0 r2 promedio =  [0.90767237 0.94632064]
7 25 0.25 r2 promedio =  [0.89723917 0.91839109]
7 25 0.5 r2 promedio =  [0.90402379 0.94313442]
7 25 0.75 r2 promedio =  [0.90406316 0.94513548]
7 25 1.0 r2 promedio =  [0.90461983 0.94559724]
7 50 0.25 r2 promedio =  [0.89234868 0.92155267]
7 50 0.5 r2 promedio =  [0.90003696 0.94188462]
7 50 0.75 r2 promedio =  [0.90075178 0.94409387]
7 50 1.0 r2 promedio =  [0.90132719 0.9442256 ]
None 1 0.25 r2 promedio =  [0.90554509 0.93059532]
None 1 0.5 r2 promedio =  [0.91184475 0.94493305]
None 1 0.75 r2 promedio =  [0.91228953 0.94717174]
None 1 1.0 r2 promedio =  [0.91274177 0.94783499]
None 5 0.25 r2 promedio =  [0.90607499 0.93270246]
None 5 0.5 r2 promedio =  [0.90979822 0.94600304]
None 5 0.75 r2 promedio =  [0.91084935 0.94686682]
None 5 1.0 r2 promedio =  [0.91229786 0.94840098]
None 25 0.25 r2 promedio =  [0.90256701 0.92911653]
None 25 0.5 r2 promedio =  [0.90830657 0.94570749]
None 25 0.75 r2 promedio =  [0.90925865 0.9462877 ]
None 25 1.0 r2 promedio =  [0.90922673 0.9474717 ]
None 50 0.25 r2 promedio =  [0.89957491 0.93027332]
None 50 0.5 r2 promedio =  [0.90373049 0.94515811]
None 50 0.75 r2 promedio =  [0.90586692 0.9465156 ]
None 50 1.0 r2 promedio =  [0.90583184 0.94692118]

Ahora repetimos el experimento para ambos modelos tomando sólo el año 2012.

In [56]:
X_original, X_reg, target = get_data()
mascara_clima = X_original['weathersit'] != 4
X_original = X_original[mascara_clima]
target = target[mascara_clima]
mascara_2012 = X_original['yr'] == 1
X_original = X_original[mascara_2012]
target = target[mascara_2012]
X_reg = X_original.drop(['dteday'],axis=1)
X_reg_train, X_reg_test, target_train, target_test = train_test_split(X_reg, target, test_size=0.1, random_state=42,
                                                                      stratify=X_reg['weathersit'])
lista_max_depth = [3,5,7,None]
lista_min_samples_split = [2,5,25,50]
lista_max_features = ['sqrt',None]
regresion_random_forest(lista_max_depth,lista_min_samples_split,lista_max_features,X_reg_train,target_train)

3 2 sqrt r2 promedio =  [0.56144173 0.39320557]
3 2 None r2 promedio =  [0.61055489 0.49033031]
3 5 sqrt r2 promedio =  [0.56144173 0.39320557]
3 5 None r2 promedio =  [0.61055489 0.49033031]
3 25 sqrt r2 promedio =  [0.56144173 0.39304784]
3 25 None r2 promedio =  [0.61055489 0.49033031]
3 50 sqrt r2 promedio =  [0.56122967 0.39233422]
3 50 None r2 promedio =  [0.61055489 0.49033031]
5 2 sqrt r2 promedio =  [0.71842236 0.52862143]
5 2 None r2 promedio =  [0.80371167 0.77339144]
5 5 sqrt r2 promedio =  [0.71682417 0.5304172 ]
5 5 None r2 promedio =  [0.80370919 0.77339284]
5 25 sqrt r2 promedio =  [0.72154269 0.52675866]
5 25 None r2 promedio =  [0.80370249 0.77339659]
5 50 sqrt r2 promedio =  [0.71945193 0.5360724 ]
5 50 None r2 promedio =  [0.80375154 0.77336719]
7 2 sqrt r2 promedio =  [0.81130487 0.66023885]
7 2 None r2 promedio =  [0.85589007 0.88490568]
7 5 sqrt r2 promedio =  [0.80565287 0.65095154]
7 5 None r2 promedio =  [0.85587374 0.88491413]
7 25 sqrt r2 promedio =  [0.80509835 0.65390112]
7 25 None r2 promedio =  [0.85501156 0.88481104]
7 50 sqrt r2 promedio =  [0.78750006 0.63682554]
7 50 None r2 promedio =  [0.8528308  0.88384809]
None 2 sqrt r2 promedio =  [0.90777485 0.88161199]
None 2 None r2 promedio =  [0.91357854 0.94274751]
None 5 sqrt r2 promedio =  [0.90172721 0.87327233]
None 5 None r2 promedio =  [0.91173285 0.94257024]
None 25 sqrt r2 promedio =  [0.8624634  0.81812707]
None 25 None r2 promedio =  [0.89899901 0.93384954]
None 50 sqrt r2 promedio =  [0.83101349 0.77715231]
None 50 None r2 promedio =  [0.88705979 0.92278485]

In [58]:
X_original, X_reg, target = get_data()
mascara_clima = X_original['weathersit'] != 4
X_original = X_original[mascara_clima]
target = target[mascara_clima]
mascara_2012 = X_original['yr'] == 1
X_original = X_original[mascara_2012]
target = target[mascara_2012]
X_reg = X_original.drop(['dteday'],axis=1)
X_reg_train, X_reg_test, target_train, target_test = train_test_split(X_reg, target, test_size=0.1, random_state=42,
                                                                      stratify=X_reg['weathersit'])
lista_max_depth = [3,5,7,None]
lista_min_samples_leaf = [1,5,25,50]
lista_max_features = [0.25,0.5,0.75,1.0]
regresion_hist_boosting(lista_max_depth,lista_min_samples_leaf,lista_max_features,X_reg_train,target_train)

3 1 0.25 r2 promedio =  [0.83138551 0.75357682]
3 1 0.5 r2 promedio =  [0.84949426 0.86742961]
3 1 0.75 r2 promedio =  [0.8498726  0.86685619]
3 1 1.0 r2 promedio =  [0.84963113 0.87926312]
3 5 0.25 r2 promedio =  [0.83112521 0.7481359 ]
3 5 0.5 r2 promedio =  [0.84917827 0.87216396]
3 5 0.75 r2 promedio =  [0.84832725 0.86996284]
3 5 1.0 r2 promedio =  [0.85076391 0.88134541]
3 25 0.25 r2 promedio =  [0.82969928 0.74705616]
3 25 0.5 r2 promedio =  [0.84526787 0.8702491 ]
3 25 0.75 r2 promedio =  [0.84493629 0.86856378]
3 25 1.0 r2 promedio =  [0.8471917  0.87872047]
3 50 0.25 r2 promedio =  [0.82781365 0.74586737]
3 50 0.5 r2 promedio =  [0.84361856 0.86728616]
3 50 0.75 r2 promedio =  [0.84377862 0.87125027]
3 50 1.0 r2 promedio =  [0.84640367 0.88162299]
5 1 0.25 r2 promedio =  [0.89999959 0.89628508]
5 1 0.5 r2 promedio =  [0.90999978 0.93784545]
5 1 0.75 r2 promedio =  [0.91035759 0.94151278]
5 1 1.0 r2 promedio =  [0.91037661 0.94146305]
5 5 0.25 r2 promedio =  [0.898969   0.89347208]
5 5 0.5 r2 promedio =  [0.90699001 0.93716247]
5 5 0.75 r2 promedio =  [0.90855632 0.9409801 ]
5 5 1.0 r2 promedio =  [0.90937526 0.94167219]
5 25 0.25 r2 promedio =  [0.89170455 0.89094696]
5 25 0.5 r2 promedio =  [0.89988687 0.9354938 ]
5 25 0.75 r2 promedio =  [0.90229245 0.93916568]
5 25 1.0 r2 promedio =  [0.90233454 0.9397603 ]
5 50 0.25 r2 promedio =  [0.88559746 0.89240351]
5 50 0.5 r2 promedio =  [0.89517135 0.93251808]
5 50 0.75 r2 promedio =  [0.89596304 0.93564728]
5 50 1.0 r2 promedio =  [0.89825718 0.9373471 ]
7 1 0.25 r2 promedio =  [0.91369709 0.92023958]
7 1 0.5 r2 promedio =  [0.92003824 0.94690553]
7 1 0.75 r2 promedio =  [0.91953091 0.94764698]
7 1 1.0 r2 promedio =  [0.92098183 0.94844226]
7 5 0.25 r2 promedio =  [0.91261004 0.91811749]
7 5 0.5 r2 promedio =  [0.919009   0.94611876]
7 5 0.75 r2 promedio =  [0.9196833  0.94854684]
7 5 1.0 r2 promedio =  [0.91997135 0.94834607]
7 25 0.25 r2 promedio =  [0.90513306 0.92178238]
7 25 0.5 r2 promedio =  [0.91243419 0.94494813]
7 25 0.75 r2 promedio =  [0.91330162 0.94740829]
7 25 1.0 r2 promedio =  [0.91316535 0.94705876]
7 50 0.25 r2 promedio =  [0.90021071 0.92234445]
7 50 0.5 r2 promedio =  [0.90752911 0.94346984]
7 50 0.75 r2 promedio =  [0.90939163 0.9457539 ]
7 50 1.0 r2 promedio =  [0.90928748 0.9459079 ]
None 1 0.25 r2 promedio =  [0.91719545 0.92837469]
None 1 0.5 r2 promedio =  [0.9226999  0.94711942]
None 1 0.75 r2 promedio =  [0.92188212 0.94900344]
None 1 1.0 r2 promedio =  [0.92255796 0.94937987]
None 5 0.25 r2 promedio =  [0.91646827 0.93064891]
None 5 0.5 r2 promedio =  [0.92068742 0.94827443]
None 5 0.75 r2 promedio =  [0.92197689 0.94871995]
None 5 1.0 r2 promedio =  [0.9221588  0.94930376]
None 25 0.25 r2 promedio =  [0.91185097 0.93087649]
None 25 0.5 r2 promedio =  [0.91710743 0.94702401]
None 25 0.75 r2 promedio =  [0.9175992  0.94861349]
None 25 1.0 r2 promedio =  [0.91656486 0.94887661]
None 50 0.25 r2 promedio =  [0.90643596 0.9277986 ]
None 50 0.5 r2 promedio =  [0.91290001 0.94638446]
None 50 0.75 r2 promedio =  [0.91320274 0.94669342]
None 50 1.0 r2 promedio =  [0.91491595 0.94798174]

Observamos que la calidad de ambos modelos va mejorando a medida que se les permite más profundidad a los árboles, y que el HistGradientBoostingRegresor es superior al RandomForestRegresor. Elegiremos nuestro modelo definitivo entre los mejores del boosting, que tienen R^2 mayor a 0.9 tanto para casual como para registered, lo que consideramos un excelente resultado.

Aunque los valores más altos se encuentran cuando los árboles no tienen profundidad limitada (max_depth = None), elegiremos un modelo entre los de max_depth = 7, ya que también logran muy buenos resultados y creemos que van a sobreajustar menos. Como queremos predicciones para años futuros, elegimos un modelo a partir de los resultados para el caso donde se excluyó el año 2011. Concretamente, tomaremos el HistGradientBoostingRegresor con max_depth = 7, min_samples_split = 1 y max_features = 1.0, cuyos R^2 scores son: [0.92098183 0.94844226] (para casual y registered respectivamente).

Ya con este modelo elegido, vamos a evaluar su resultado con los datos de evaluación, y luego construiremos las predicciones de cnt sumando las de casual y registered. Luego de aplicar la suma redondeamos ya que se debe predecir valores enteros (uso de bicicletas en el día).

In [68]:
X_original, X_reg, target = get_data()
mascara_clima = X_original['weathersit'] != 4
X_original = X_original[mascara_clima]
target = target[mascara_clima]
mascara_2012 = X_original['yr'] == 1
X_original = X_original[mascara_2012]
target = target[mascara_2012]
X_reg = X_original.drop(['dteday'],axis=1)
X_reg_train, X_reg_test, target_train, target_test = train_test_split(X_reg, target, test_size=0.1, random_state=42,
                                                                      stratify=X_reg['weathersit'])

In [69]:
modelo_final_1 = HistGradientBoostingRegressor(max_depth=7,min_samples_leaf=1,max_features=1.0,loss='squared_error')
modelo_final_2 = HistGradientBoostingRegressor(max_depth=7,min_samples_leaf=1,max_features=1.0,loss='squared_error')
modelo_final_1.fit(X_reg_train,target_train['casual'])
modelo_final_2.fit(X_reg_train,target_train['registered'])
pred_casual = modelo_final_1.predict(X_reg_test)
pred_registered = modelo_final_2.predict(X_reg_test)
pred_cnt = np.round(pred_casual+pred_registered,0)

In [70]:
pred_cnt

array([ 19., 141., 173., 384.,  14., 279.,  21.,   0., 672., 285.,  37.,
        60., 607., 490., 647.,  27.,  19.,  71., 499.,  47., 198., 293.,
       192., 129., 208., 469.,  99., 535., 472.,  52., 120., 205.,  56.,
       305., 313., 389., 219., 305., 188., 456., 126., 189.,  96., 897.,
       194.,  29., 513., -13., 195., 351., 764., 190., 281., 242.,  18.,
        70., 419., 394.,  12.,  53.,  11., 632., 396.,  73., 338.,  13.,
        14.,   3., 233., 436.,  13., 284.,  12.,  17., 701., 499., 227.,
       340., 155., 618., 421., 615., 270., 575., 167., 511., -12.,  30.,
       196.,  50., 483.,  27., 207., 184., 465., 509., 438., 134.,  73.,
       528.,  13., 117., 316., 215.,  40., 442., 130., 278., 201., 514.,
       166., 128., 114., 113., 180., 432.,  50.,  18., 218.,  91., 513.,
       217., 305.,  28., 433.,  42., 168.,  42., 228., 139.,   7., 574.,
       217., 556., 228., 365., 403., 295., 175., 152.,  14., 434.,  44.,
       688., 380., 342.,  96.,  82.,  11., 214.,   8., 300., 265., 242.,
       310., 308.,  96., 585., 114.,  17.,  64., 228., 278., 201., 303.,
       276.,   6., 399.,  39., 229., 498.,  13.,  10., 412., 258.,  94.,
         9., 499., 229., 542., 324., 233., 428., 182., 706., 193., 154.,
        48., 197., 332.,  12., 354., 254.,  30., 100., 174., 165.,  18.,
        12., 183., 149., 144., 448., 285.,  17., 448.,  20., 310.,  -5.,
        17.,   5.,  -0., 314., 526., 177., 322., 301., 281., 240.,   7.,
        -4.,  35.,  19.,   9., 116., 186., 351., 657., 222.,  18.,  21.,
       111., 116.,  62., 246.,   3., 367., 494.,   3., 423., 151., 720.,
       193.,   8., 118.,  78., 134.,  10., 190.,  12., 225.,  20., 177.,
       159., 686., 411., 169.,  29., 796., 195., 406., 716., 463., 261.,
        31.,  34., 294., 310., 191., 351.,  43., 303.,  44.,   7.,  24.,
       189.,  32.,  18.,  36., 133., 205., 196.,  11., 262.,  71., 125.,
       379., 276., 418., 412., 230., 172., 264., 370., 795., 297.,   4.,
       121., 303., -12., 159.,  82., 341., 432.,  -1., 355.,  15., 286.,
       618., 103., 702., 249.,  -5.,  22., 279., 767.,  43., 831.,  26.,
       510.,  58., 336., 222., 110.,  29., -10., 220.,  23., 117., 266.,
       404., 205., 365., 525., 226., 602., 133.,  10., 374.,   6.,  21.,
       716.,  43., 183., 617., 385.,  29.,  17., 250., 425., 106., 264.,
       311., 448., 340.,  13., 135., 247., 200., 623.,  20., 295., 361.,
       247., 345.,  77.,  92.,  78., 364., 274., 315.,  16., 584., 720.,
       137., 138.,   7., 320., 219.,  39.,  95., 757., 170.,  51.,  53.,
       249., 137., 275.,  -8., 109., 120., 336., 436., 299., 290.,  23.,
       392., 373., 813., 327.,  97.,  40., 165., 167., 412.,  15., 518.,
       490.,  43., 656., -10., 238., 151., 182.,  30., 283., 364.,  12.,
        41., 149.,  19.,  83., 374.,  65.,  10.,  34.,  25., 488., 255.,
       139., 585.,  14., 366.,  29., 567.,  62.,  57., 407., 743., 267.,
       394., 355., 110., 166., 517., 389., 205.,  31., 431., 298., 413.,
       426., 229.,  20., 351.,  79., 554.,  94., 416., 365.,  17., 598.,
        23., 284., 282., 232., 171.,  86., 434., 134.,  23.,  11., 124.,
       323., 319., 110., 121., 253., 271., 127., 119., 220., 428.,   6.,
       262., 266.,   8., 158.,   4.,  10., 266., 396.,   4., 341., 244.,
        19., 232., 812., 387.,  22., 362., 149., 181., 167., 183., 154.,
       289.,  27., 335., 199.,   9., 207., 178., 452.,  16., 274., 566.,
       243.,  32., 159., 273., 488., 455., 721.,  13., 250., 317., 363.,
       521.,  -5.,  -3.,  99.,  16.,  80., 409., 579., 444., 284.,  36.,
         3.,  20., 770.,  69., 410., 294.,  16., 619., 325., 343.,  19.,
        71., 443., 234., 131., 303., 309.,  56.,  28., 100., 342., 504.,
       202., 365., 416.,  13., 244., 345.,  91., 385., 598.,   3.,  65.,
       578.,   4., 679., 243.,   9., 213., 183., 212., 149.,  10., 126.,
       284., 507., 301., -17., 407., 267., 251.,  32.,   7.,  25.,  26.,
       194., 265.,  -2.,  18.,  44., 616.,  14., 768., 234., 892., 176.,
       272.,  66., 428., 713., 785., 301.,  85., 437., 191., 328., 103.,
       462.,  34., 265.,  87., 466.,  13., 388., 186., 234.,  93.,  95.,
       249., 648., 312.,  28.,  -5., 122., 405.,  94., 569., 301., 532.,
       789., 250., 549.,  16., 462.,  21., 213.,  79.,  87., 355., 395.,
        -1., 184., 277., 550., 446., 245., 266., 373., 160., 259., 155.,
       223.,   6., 240., 108., 623., 239., 653.,  14., 113., 402.,   8.,
       446., 347., 165.,  96., 518., 515.,  12., 355., 114., 408., 818.,
         5., 249., 126.,  15., 561.,   2., 437.,  47., 687., 500., 143.,
       353.,  59.,  81., 291.,  99.,   4.,  32., 482., 139., 106., 162.,
       113., 795.,  29., 446., 457.,  16., 185.,  43., 256.,  18., 306.,
       455., 119., 171., 189., 310.,   5., 583., 236.,  16., 222., 595.,
       343.,   9., 506., 719.,  16., 294.,  89., 104., 273.,  41., 164.,
       164., 270., 222., 317.,  39.,  30., 131., 237.,  79., 683.,   7.,
       447., 264., 339., 589., 322., 643., 683., 436., 622., 168., 101.,
        65.,  15., 256., 152., 774., 104., 195., 441., 710., 249., 348.,
        79.,  33., 300.,  16., 628.,  61.,  11., 523.,  46.,  48., 266.,
       327., 597., 151.,  43., 156.,  87., 244., 444., 299., 572., 434.,
       186.,  18., 291.,  55.,  13., 379., 129., 173.,   9.,   9., 244.,
       159., 171., 300.,  11.,  17., 258.,  14., 402., 318., 495., 371.,
       372., 170., 122., 230., 113., 138.,  50.,  17., 193.,  27., 421.,
       273., 118., 189.,  43., 624.,  41.,  19., 476.,   9., 133., 360.,
       246., 141.,  26.,  71., 519., 582., 568., 243.,  81.,  24.,  13.,
       148., 538.,  47., 221., 289., 332.,   9., 441., 330.,  35.,  51.,
       155., 137.,  61., 270., 288.,   8.,  88., 380., 136.,  29., 175.,
       240., 306.,  18., 476., 162.])

In [71]:
target_test

       casual  registered  cnt
14781       0           9    9
17275      23         151  174
9711       13         111  124
13159     124         218  342
10681       0           4    4
...       ...         ...  ...
16213       1         106  107
14455      73         221  294
16809       3           9   12
16318     144         325  469
17103      23         138  161

[874 rows x 3 columns]

In [72]:
r2_score(target_test.iloc[:,0],pred_casual)

0.9134097229047091

In [73]:
r2_score(target_test.iloc[:,1],pred_registered)

0.9569765130369485

In [74]:
mean_squared_error(target_test.iloc[:,0],pred_casual)

276.8215591921389

In [76]:
mean_squared_error(target_test.iloc[:,1],pred_registered)

1304.554230969874

In [62]:
print(pred_cnt-np.array(target_test.iloc[:,2]))

[  10.  -33.   49.   42.   10.   11.    2.   -2.    8.  -15.  -18.   28.
   11.  374.    7.  -11.   -9.    5.   83.   13.  108.  -38.   62.   13.
    5.  -37.    7.   19.  -83.   31.   90.   11.    2.  -12.  -22.   48.
  -15.  -73.   27. -111.   27.   -2.   73.  -41.   22.   19.  -50.  -22.
  -24.  -22.   12.   33.   21.  -25.  -16.   17.   11.  -51.    7.    0.
   -9. -125.  -28.   19.   65.    7.    2.   -1.    9. -148.    1.   21.
    6.    7.   -1.   35.  -36.   36.    1.   50.    3.  -73.  -40.   50.
   13. -103.  -19.  -16.  -25.   36.   64.  -16.   -2.  -19.  -65.  -13.
  -33.   30.    7.  -11.    3.   -6.  -18.   27.   14.  -30.   16.  -51.
    0.  -67.  -24.  -20.   27.   13.    8.  132.   18.   16.  -66.    3.
   30.   36.  -37.  -26.   22.  -13.   -3.   13.   49. -105.    3.  -88.
  -28.  -89.   24.   62.  -40.   80.   -7.  -15.  -22.  -41.    8.   14.
 -111.   -9.  -17.  -23.    2.    3.    7.  -97.   -3.  114.  -69.   53.
  -21.    9.   32.  -10.   19.   51.   59.   48.   50.    0.   -1.  -55.
   -9.   39.   49.    4.    2.   32.    7.    1.    5.  -33.  131.  -33.
   -8.  -25.  -13.    1.   63.    2.   -4.  -22.   27.  -19.    4.   14.
  -59.   14.   51.   -8.   17.    0.    4.    5.  -11.    9.   18.   -3.
   -4.  157.   -1.   23.  -18.    6.    4.   -8.   12.  101.   68.   -9.
  -39.   29.   22.    0.   -9.    6.    2.    7.   16.   23.   23.   72.
  -38.  -17.   10.   47.    5.   -1.    2.    2.   20.   21.   -1.    4.
  -38.   -5.  -57.    7.   32.   11.  -24.    5.  -45.  -19.   79.  -11.
   21.   18.   31.    5.   10.   -7.  -51.   11.   15. -101.  -20.  -27.
   20.    2.    9.   32.  -26.  -28.    0.   27.   -8.    4.   -1.   -2.
  -18.   -5.    9.   11.  -28.  -20.   -3.  -11.    7.   16.  -31.  -23.
   -7.   35.   34.  -54.  -68.   36.  -18.   39.   -1.   35.   46.  -23.
   15.  -20.  -83.  -17.   -7.    0.   -1.  -71.   58.   27.   33.  -27.
   -9.   12.   14.   26.  -17.   -3.   -3.  -47.   -2.    1.   28.   -1.
   25.  -12.    4.    0.   68.   46.  -13.  -12.   30.   11.   15.  -92.
   -3.    2.  -15.    4.  -65.   11.   -2.  132.   -9.    3.   -9.  -31.
  -21.  -54.  -13.  -20.   10.  -44.  -20.    3.   13.   -4.  -45.   42.
  -20.    4.   29.  -33.  -28.    1.  -11.  -36.   14.    9.   12.    2.
   -1.  -20.   28.   -2.  -18.   25.  -69.   20.   15.  -29.  -20.   -1.
   -2.   -6.  -24.  -66.  -13.  -32.   13.   80.  -87.  -30.   65.    2.
   49.   20.  -17.  142.   -3.  -19.    0.   22.  -29.   -3.   49.   91.
    6.   88.  -40.  -16.  -41.  -11.  -15.  -48.  -29.   10.   21.   15.
    0.   32.    9.  -17.    5.   -8.   -1.   21.  -14.    7.  -30.   11.
  -21.   17.  -28.    3.   20.  -93.  -12.  125.   13.  -13.   14.  -34.
   11.   -7.  -27.  -22.   28.    7.  264.   13.  -16.   11.    9.   19.
  -31.  -12.   -4.   -6.    8.    8.   13.   -1.   44.  -18.   41.   16.
  -54.  -15.    7.   10.   -6.  -46. -112.  -43.    5.   35.   17.   63.
   -2.   81.  -38.   -1.   32.   34.   -1.   -6.  -22.    3.   64.   -8.
    2.  -12.  -12.   11.   53.   -2.  154.    9.  -47.  -42.  -26.   91.
  -19.   11.  112.    2.   -8.  -33.   -1.   52.    9.  -13.    1.   24.
   32.  -19.   21.  -31.  -24. -129.  -50.  -39.    6.   13.   35.   28.
   21.   -8.  -14.   12.    8.  -12.   51.   42.  -19.   24.   -2.   -1.
    3.  -74.    0.  -33.    6.   12.  -35.   -5.  -39.    8.    5.   -4.
   38.  -23.   -8.   -3.    8.  -11.   21.   14.    9.  -25.   11.   25.
    9.   64.   42.    8.   -3.  -80.    0.   34.  -53.   -5.   33.   24.
    7.   -3.    6.  -36.    0.   -6.   13.   15.  299.  -31.  -27.  -54.
   -5.   -6.   -5.    2.   -3.   15.   58.   -9.   -4.    2.    5.  -22.
   -2.    9.   20.  -78.    9.   25.    7.   93.  -33. -103.    0.    6.
    7.  -36.   37.   16.  -33.   21.   31.    9.  195.    8.   41.   21.
   17.  -36.  -30.  -12.   58.  -86.   14.   -8.   33.  -57.    1.  -10.
  -11.   40.   45.  128.  -29.    8.   -4.    3.    9.    1.   26.   -1.
  -18.   -7.  -59.  -10.  -35.   63.  -26.   27.  -39.   75.  -29.    3.
  -12.  -27.   23.   -3.   84.  102.   12.    5.   10.   -8.    4.  -46.
   10.   55.   15.  -37.  110.    7.   22.  -12.  -62.  -31.   -4.  -42.
   32.    9.  -61.  -10.   58.    4.  -42.   33.  -17.   46.    8.   -8.
   37.   -8.  -10.   -9.    6.   20.    6.   31.    5.  -15.    8.  -36.
    7.    4.   51.   10.   33.    3.    7.   34.   19.  -18.   22. -255.
   -1.  -66.  -17.    8.  -74. -139.    0.   -3.   45.   79.    8.   -2.
   44.   42.    4.   -7.   30.   11.  -48.   25.   20.   15.    6.   16.
   12.    9.  -39.   -6.   22.    9.   -9.  -25.  -24. -107.   24.   20.
  -17.   28.  -12.   31.    5.   19.   -2.  -20.    4.   -8.  -60.   93.
   56.  -15.  -45.    8.    0.   -2.   25.  -10.  -18.  -53.  -20.  -10.
   15.   44. -127.   -9.    3.   38.  -36.   40.  -82.  -34.  -80.    6.
   13.   -3.   -8.   -2.    7.  -29.   -2.   63.    2.    1.  -21.  -19.
  -22.  -33.    3.   10.  -47.  -18.    2.  -92.   -2.    5.    7.  -19.
   77.  -91.   25.  -76.   24.   15.    1.   -1.   52.    2.    2.   44.
    3.   57.    3.   -8.  -76.    6.  -20. -100.   54.   22.    8.   19.
  -49.    0.  -42.  -10.   -1.   21.    6.   47.  -29.   16.   49.    8.
   18.    1.  -74.   11.   10.   25.  -23.    1.    5.    5.   14.    3.
    5.    1.   24.   -7.  -23.  133.   12.    6.    7.    1.]

In [ ]:
print((pred_cnt-np.array(target_test.iloc[:,2]))/np.array(target_test.iloc[:,2]))
#calculamos los errores relativos

[ 1.11111111e+00 -1.89655172e-01  3.95161290e-01  1.22807018e-01
  2.50000000e+00  4.10447761e-02  1.05263158e-01 -1.00000000e+00
  1.20481928e-02 -5.00000000e-02 -3.27272727e-01  8.75000000e-01
  1.84563758e-02  3.22413793e+00  1.09375000e-02 -2.89473684e-01
 -3.21428571e-01  7.57575758e-02  1.99519231e-01  3.82352941e-01
  1.20000000e+00 -1.14803625e-01  4.76923077e-01  1.12068966e-01
  2.46305419e-02 -7.31225296e-02  7.60869565e-02  3.68217054e-02
 -1.49549550e-01  1.47619048e+00  3.00000000e+00  5.67010309e-02
  3.70370370e-02 -3.78548896e-02 -6.56716418e-02  1.40762463e-01
 -6.41025641e-02 -1.93121693e-01  1.67701863e-01 -1.95767196e-01
  2.72727273e-01 -1.04712042e-02  3.17391304e+00 -4.37100213e-02
  1.27906977e-01  1.90000000e+00 -8.88099467e-02 -2.44444444e+00
 -1.09589041e-01 -5.89812332e-02  1.59574468e-02  2.10191083e-01
  8.07692308e-02 -9.36329588e-02 -4.70588235e-01  3.20754717e-01
  2.69607843e-02 -1.14606742e-01  1.40000000e+00  0.00000000e+00
 -4.50000000e-01 -1.65125495e-01 -6.60377358e-02  3.51851852e-01
  2.38095238e-01  1.16666667e+00  1.66666667e-01 -2.50000000e-01
  4.01785714e-02 -2.53424658e-01  8.33333333e-02  7.98479087e-02
  1.00000000e+00  7.00000000e-01 -1.42450142e-03  7.54310345e-02
 -1.36882129e-01  1.18421053e-01  6.49350649e-03  8.80281690e-02
  7.17703349e-03 -1.06104651e-01 -1.29032258e-01  9.52380952e-02
  8.44155844e-02 -1.67752443e-01 -2.71428571e+00 -3.47826087e-01
 -1.13122172e-01  2.57142857e+00  1.52744630e-01 -3.72093023e-01
 -9.56937799e-03 -9.35960591e-02 -1.22641509e-01 -2.49042146e-02
 -7.00636943e-02  2.88461538e-01  1.06060606e-01 -2.04081633e-02
  3.00000000e-01 -4.87804878e-02 -5.38922156e-02  1.43617021e-01
  5.38461538e-01 -6.35593220e-02  1.40350877e-01 -1.55015198e-01
  0.00000000e+00 -1.15318417e-01 -1.26315789e-01 -1.35135135e-01
  3.10344828e-01  1.30000000e-01  4.65116279e-02  4.40000000e-01
  5.62500000e-01  8.00000000e+00 -2.32394366e-01  3.40909091e-02
  6.21118012e-02  1.98895028e-01 -1.08187135e-01 -4.81481481e-01
  5.35279805e-02 -2.36363636e-01 -1.75438596e-02  4.48275862e-01
  2.73743017e-01 -4.30327869e-01  7.50000000e-01 -1.32930514e-01
 -1.14285714e-01 -1.37984496e-01  1.17647059e-01  2.04620462e-01
 -9.02934537e-02  3.72093023e-01 -3.84615385e-02 -8.98203593e-02
 -6.11111111e-01 -8.63157895e-02  2.22222222e-01  2.07715134e-02
 -2.26069246e-01 -2.56410256e-02 -1.50442478e-01 -2.19047619e-01
  2.22222222e-01  1.42180095e-02  7.00000000e+00 -2.44332494e-01
 -1.11940299e-02  8.90625000e-01 -1.82058047e-01  2.07843137e-01
 -1.79487179e-01  1.56250000e-02  3.90243902e-01 -3.70370370e-01
  4.22222222e-01  2.88135593e-01  2.69406393e-01  3.13725490e-01
  1.97628458e-01  0.00000000e+00 -1.42857143e-01 -1.21145374e-01
 -1.87500000e-01  2.05263158e-01  1.09131403e-01  4.44444444e-01
  2.50000000e-01  8.42105263e-02  2.78884462e-02  1.07526882e-02
  1.25000000e+00 -6.20300752e-02  1.33673469e+00 -5.73913043e-02
 -2.40963855e-02 -9.68992248e-02 -2.94784580e-02  5.52486188e-03
  9.79782271e-02  1.04712042e-02 -2.53164557e-02 -3.14285714e-01
  1.58823529e-01 -5.41310541e-02  5.00000000e-01  4.11764706e-02
 -1.88498403e-01  8.75000000e-01  1.04081633e+00 -4.39560440e-02
  1.14864865e-01  0.00000000e+00  5.00000000e-01  2.80898876e-02
 -6.87500000e-02  6.66666667e-02  4.18604651e-02 -1.04166667e-02
 -1.90476190e-01  5.39518900e-01 -4.76190476e-02  8.01393728e-02
 -1.38461538e+00  5.45454545e-01  4.00000000e+00 -1.00000000e+00
  3.97350993e-02  2.37647059e-01  6.23853211e-01 -2.71903323e-02
 -1.14705882e-01  1.15079365e-01  1.00917431e-01  0.00000000e+00
 -1.80000000e+00  2.06896552e-01  1.17647059e-01  3.50000000e+00
  1.60000000e-01  1.41104294e-01  7.01219512e-02  1.23076923e-01
 -1.46153846e-01 -4.85714286e-01  9.09090909e-01  7.34375000e-01
  4.50450450e-02 -1.58730159e-02  8.19672131e-03  2.00000000e+00
  5.76368876e-02  4.43974630e-02 -2.50000000e-01  9.54653938e-03
 -2.01058201e-01 -6.89655172e-03 -2.28000000e-01  7.00000000e+00
  3.72093023e-01  1.64179104e-01 -1.51898734e-01  1.00000000e+00
 -1.91489362e-01 -6.12903226e-01  5.41095890e-01 -3.54838710e-01
  1.34615385e-01  1.27659574e-01  4.73282443e-02  1.23152709e-02
  6.28930818e-02 -1.94444444e-01 -6.02125148e-02  5.97826087e-02
  3.83631714e-02 -1.23623011e-01 -4.14078675e-02 -9.37500000e-02
  1.81818182e+00  6.25000000e-02  3.15789474e-02  1.15107914e-01
 -1.19815668e-01 -7.38786280e-02  0.00000000e+00  9.78260870e-02
 -1.53846154e-01  1.33333333e+00 -4.00000000e-02 -1.04712042e-02
 -3.60000000e-01 -2.17391304e-01  3.33333333e-01  9.01639344e-02
 -1.20171674e-01 -9.25925926e-02 -2.14285714e-01 -4.02930403e-02
  1.09375000e-01  1.46788991e-01 -7.56097561e-02 -7.69230769e-02
 -1.64705882e-02  9.28381963e-02  1.73469388e-01 -2.38938053e-01
 -2.04819277e-01  1.07784431e-01 -2.21402214e-02  1.51162791e-01
 -2.00000000e-01  4.06976744e-01  1.78988327e-01 -2.09090909e+00
  1.04166667e-01 -1.96078431e-01 -1.95754717e-01 -3.78619154e-02
 -1.16666667e+00  0.00000000e+00 -6.25000000e-02 -1.98879552e-01
  1.03571429e-01  3.55263158e-01  4.93273543e-02 -9.78260870e-02
 -2.25000000e+00  1.20000000e+00  5.28301887e-02  3.50877193e-02
 -2.83333333e-01 -3.59712230e-03 -1.03448276e-01 -8.43806104e-02
 -3.33333333e-02  2.98507463e-03  1.44329897e-01 -9.00900901e-03
  6.25000000e+00 -6.00000000e+00  1.85185185e-02  0.00000000e+00
  1.38775510e+00  2.09090909e-01 -3.11750600e-02 -5.52995392e-02
  8.95522388e-02  2.14007782e-02  7.10900474e-02 -1.32564841e-01
 -2.20588235e-02  2.50000000e-01 -3.85604113e-02  2.00000000e+00
 -7.55813953e-01  1.56028369e-02 -4.44444444e-02  2.58823529e+00
 -1.43769968e-02  7.85340314e-03 -2.36842105e-01 -6.45833333e-01
 -7.74907749e-02 -1.12734864e-01 -1.09243697e-01 -7.04225352e-02
  3.32225914e-02 -8.94308943e-02 -5.55555556e-02  3.00000000e-01
  1.06557377e-01 -1.59362550e-02 -1.83673469e-01  7.22891566e-02
 -5.00000000e-01  1.37457045e-02  8.73493976e-02 -1.17857143e-01
 -7.50670241e-02  1.31578947e-02 -1.06796117e-01 -3.15789474e-01
  4.00000000e-02  3.39622642e-02  3.96039604e-02  1.42857143e-01
 -1.70940171e-03 -2.70270270e-02  2.56880734e-01 -1.42857143e-02
 -7.20000000e-01  8.47457627e-02 -2.39583333e-01  1.05263158e+00
  1.87500000e-01 -3.68956743e-02 -1.05263158e-01 -1.92307692e-02
 -3.63636364e-02 -2.35294118e-02 -1.49068323e-01 -1.93548387e-01
 -2.60000000e+00 -2.26950355e-01  1.21495327e-01  3.12500000e-01
 -1.66347992e-01 -9.11854103e-02  2.88888889e-01  9.52380952e-02
  1.42857143e-01  5.66572238e-02 -2.04819277e-02  7.67567568e-01
 -3.00000000e-02 -3.22033898e-01  0.00000000e+00  1.51724138e-01
 -6.57596372e-02 -1.66666667e-01  1.04477612e-01  2.28070175e-01
  1.62162162e-01  1.54929577e-01 -1.33333333e+00 -6.29921260e-02
 -2.13541667e-01 -5.69948187e-02 -3.33333333e-01 -1.45015106e-01
 -7.37913486e-02  5.00000000e+00  1.05000000e+00  1.11940299e-01
  0.00000000e+00  6.27450980e-01  2.46575342e-02 -2.07317073e-01
  1.00000000e+00 -1.90476190e-01 -3.84615385e-02  4.49678801e-02
 -5.20446097e-02  5.30303030e-02 -4.87804878e-02  3.66666667e+00
 -5.42635659e-02  1.41666667e+00 -4.70588235e-02  5.08474576e-02
  5.40540541e-01 -1.86000000e-01 -1.58940397e-02  8.80281690e-01
  3.41207349e-02 -3.53260870e-02  1.45833333e-01 -1.70000000e-01
  2.17391304e-02 -1.76767677e-02 -1.16379310e-01 -4.15094340e-01
  6.94789082e-02  2.40549828e-02  1.77181208e+00  3.14769976e-02
 -6.53061224e-02  1.22222222e+00  2.63157895e-02  3.16666667e-01
 -5.29914530e-02 -1.13207547e-01 -9.52380952e-03 -1.61725067e-02
  8.88888889e-01  1.35593220e-02  1.30000000e+00 -3.50877193e-03
  1.84873950e-01 -7.20000000e-02  3.15384615e-01  2.28571429e-01
 -1.10655738e-01 -1.00671141e-01  4.37500000e-01  1.00000000e+01
 -4.61538462e-02 -1.24661247e-01 -2.59860789e-01 -2.81045752e-01
  4.31034483e-02  1.60550459e-01  6.69291339e-02  9.84375000e-01
 -1.65289256e-02  5.82733813e-01 -8.15450644e-02 -1.42857143e-01
  1.39130435e-01  1.46551724e-01 -1.11111111e-01 -3.65853659e-02
 -8.46153846e-01  4.28571429e-01  3.16831683e-01 -1.98019802e-02
  1.00000000e+00 -3.39943343e-02 -4.68750000e-02  1.37500000e+00
  2.96089385e-01 -2.45700246e-03  6.60944206e-01  6.92307692e-01
 -1.14914425e-01 -2.19895288e-01 -1.25603865e-01  1.19736842e+00
 -9.40594059e-02  7.69230769e-02  6.32768362e-01  8.00000000e-02
 -2.33236152e-02 -1.42241379e-01 -1.00000000e-01  3.35483871e-01
  5.32544379e-02 -2.79569892e-02  6.66666667e-02  9.60000000e-02
  5.99250936e-02 -7.25190840e-02  1.90909091e+00 -1.63157895e-01
 -8.08080808e-02 -2.09076175e-01 -9.90099010e-02 -5.13157895e-02
  8.57142857e-01  5.48523207e-02  1.24113475e-01  8.35820896e-02
  4.20000000e-02 -2.66666667e+00 -1.27272727e+00  1.37931034e-01
  1.00000000e+00 -1.30434783e-01  1.42458101e-01  7.82122905e-02
 -4.10367171e-02  9.23076923e-02 -5.26315789e-02 -2.50000000e-01
  1.76470588e-01 -8.76777251e-02  0.00000000e+00 -7.44920993e-02
  2.08333333e-02  3.00000000e+00 -5.35168196e-02 -1.51515152e-02
 -1.02094241e-01  7.27272727e-01  7.57575758e-02 -8.94854586e-03
  1.93877551e-01 -1.49350649e-01 -2.57234727e-02 -9.61538462e-03
  1.66666667e-01 -2.82051282e-01  2.65822785e-01  4.26829268e-02
  1.81818182e-02 -1.10132159e-01  3.10734463e-02  6.39386189e-02
  2.25000000e+00  3.55555556e-01  1.38613861e-01  9.63855422e-02
 -7.73195876e-03 -1.17994100e-01  0.00000000e+00  1.09677419e+00
 -8.39936609e-02 -5.55555556e-01  5.10835913e-02  1.09589041e-01
  3.50000000e+00 -1.38888889e-02  3.38983051e-02 -1.45161290e-01
  0.00000000e+00 -3.75000000e-01  1.15044248e-01  5.57620818e-02
  1.43750000e+00 -9.33734940e-02 -2.70000000e+00 -1.17136659e-01
 -1.83823529e-02 -2.33463035e-02 -1.35135135e-01  4.00000000e-01
 -1.07142857e-01  1.36363636e+00  4.26470588e-01 -3.28467153e-02
 -2.00000000e+00  1.25000000e-01  1.28205128e-01 -3.44827586e-02
 -1.25000000e-01  1.18577075e-02  9.34579439e-02 -8.04123711e-02
  5.38922156e-02  1.01214575e-01  1.18644068e-01  2.77611940e-01
 -4.42359249e-02 -1.15990991e-01  0.00000000e+00  7.59493671e-02
  1.62790698e-02 -1.58590308e-01  1.27147766e-01  1.83908046e-01
 -6.66666667e-02  1.61538462e+00  1.32478632e-01  1.15384615e-01
  7.19557196e-01  1.60000000e+00  1.18155620e-01  1.27272727e-01
  7.83410138e-02 -2.79069767e-01 -2.40000000e-01 -4.59770115e-02
  9.83050847e-02 -2.16080402e-01  1.00000000e+00 -2.66666667e+00
  3.70786517e-01 -1.23376623e-01  1.07526882e-02 -1.72711572e-02
 -3.52564103e-02  8.13008130e-02  6.04838710e-02  1.04918033e+00
 -5.01730104e-02  1.00000000e+00 -8.58369099e-03  1.66666667e-01
  4.41176471e-02  1.28205128e-02  4.26229508e-01 -2.80898876e-03
 -4.35835351e-02 -1.16666667e+00 -2.42798354e-01 -3.48432056e-02
 -5.98290598e-02  1.64490862e-01 -9.59409594e-02  1.12970711e-01
 -9.46601942e-02  8.82352941e-01 -1.00694444e-01  1.97368421e-02
 -5.10638298e-02 -8.18181818e-01  1.05990783e-01 -2.70270270e-02
  1.55844156e-01  7.44525547e-01  1.87207488e-02  5.55555556e-01
  9.70873786e-02 -1.95121951e-02  1.00000000e+00 -9.34959350e-02
  2.96735905e-02  5.00000000e-01  1.85185185e-01 -6.66666667e-02
  2.71604938e-01  1.40000000e+00  6.60660661e-02 -9.52380952e-02
 -1.31914894e-01 -3.65135453e-02 -4.44444444e-01 -1.44329897e-01
  3.40425532e-01  1.50000000e+00 -9.80707395e-02 -8.33333333e-01
  1.53034301e-01  9.30232558e-02 -5.76131687e-02  7.06638116e-02
 -1.06250000e-01  1.49837134e-01  1.56862745e-01 -8.98876404e-02
  1.45669291e-01 -7.47663551e-02 -7.14285714e-01 -2.19512195e-01
  1.26050420e-02  1.68067227e-01  6.00000000e-02  2.36641221e-01
  4.62962963e-02 -1.85185185e-02  3.80952381e-01 -7.46887967e-02
  1.55555556e-02  3.33333333e-01  3.80597015e-01  3.03030303e-01
  1.47982063e-01  2.00000000e-01  2.34113712e-02  8.07600950e-02
  1.90000000e-01 -9.52380952e-02  1.31736527e-01 -4.51327434e-01
 -1.66666667e-01 -1.01694915e-01 -6.71936759e-02  1.00000000e+00
 -2.50000000e-01 -1.89373297e-01  0.00000000e+00 -2.50000000e-01
  9.76138829e-02  1.23437500e-01  1.00000000e+00 -6.75675676e-03
  9.77777778e-01  6.77419355e-01  1.48698885e-02 -1.45833333e-01
  2.23880597e-01  7.18954248e-02 -1.50943396e-01  1.26903553e-01
  6.73400673e-02  6.25000000e-01  2.50000000e-01  1.39130435e-01
  5.33333333e-02  1.28571429e-01 -5.40166205e-02 -4.61538462e-01
  5.17647059e-02  3.52941176e-02 -2.58620690e-02 -4.07166124e-02
 -6.93641618e-02 -1.42666667e-01  3.64188164e-02  4.80769231e-02
 -2.66040689e-02  2.00000000e-01 -1.06194690e-01  9.11764706e-01
  5.00000000e-01  8.01687764e-02 -1.29870130e-02 -2.51889169e-02
  4.00000000e-02 -3.94088670e-02 -1.19760479e-01  1.50729335e-01
  2.90155440e-01 -4.13223140e-02 -3.62903226e-01  3.20000000e-01
  0.00000000e+00 -1.11111111e-01  4.14593698e-02 -1.40845070e-01
 -6.20689655e-01 -9.20138889e-02 -3.03030303e-01 -1.72413793e-01
  5.97609562e-02  1.55477032e-01 -1.75414365e-01 -5.62500000e-02
  7.50000000e-02  3.22033898e-01 -2.92682927e-01  1.96078431e-01
 -1.55893536e-01 -1.02102102e-01 -1.22699387e-01  1.40186916e-02
  7.51445087e-02 -1.42857143e-01 -2.67558528e-02 -3.50877193e-02
  1.16666667e+00 -7.10784314e-02 -1.52671756e-02  5.72727273e-01
  2.85714286e-01  1.25000000e-01 -7.92452830e-02 -1.06741573e-01
 -1.13989637e-01 -9.90990991e-02  3.75000000e-01  1.42857143e+00
 -1.54098361e-01 -5.62500000e-01  5.00000000e-03 -2.24390244e-01
 -4.02414487e-03  1.36612022e-02  1.91780822e-02 -1.00529101e-01
  1.71111111e+00 -2.83489097e-01  2.84090909e-01 -3.55140187e-01
  9.23076923e-01  7.50000000e+00  5.20833333e-03 -3.57142857e-02
  1.40921409e-01  7.38007380e-03  1.72413793e-02  3.03448276e-01
  7.50000000e-02  1.00529101e-01  7.89473684e-02 -2.96296296e-01
 -1.37681159e-01  2.00000000e+00 -1.30718954e-01 -2.17391304e-01
  2.81250000e-01  1.84873950e-01  4.44444444e-01  3.65384615e-01
 -8.62676056e-02  0.00000000e+00 -6.88524590e-02 -3.95256917e-02
 -1.21951220e-02  7.00000000e+00  8.57142857e-01  4.65346535e-01
 -5.11463845e-02  5.16129032e-01  2.84883721e-01  2.84697509e-02
  5.73248408e-02  1.25000000e-01 -1.43689320e-01  3.44827586e-02
  4.00000000e-01  9.61538462e-01 -1.29213483e-01  7.35294118e-03
  8.92857143e-02  1.88679245e-02  5.10948905e-02  6.00000000e-01
  6.02409639e-02  2.63852243e-03  2.14285714e-01 -1.94444444e-01
 -1.16161616e-01  1.24299065e+00  4.08163265e-02  5.00000000e-01
  1.49253731e-02  6.21118012e-03]

Al menos en muchos casos hemos conseguido errores en cnt menores al 10% (los de orden e-2, e-3 o menores), aunque en otros hemos cometido errores mayores. Llegamos a la conclusión de que es un resultado aceptable para un problema que intrínsecamente es ruidoso por depender de la decisión de mucha gente de subirse o no a una bicicleta, aunque la confianza que se puede tener en nuestro modelo por sí solo es limitada. Hemos logrado muy buenos valores de R^2 como son 0,91 para casual y 0,96 para registered, lo que al menos indica que nuestro modelo es muy superior al predictor "dummy" que sería predecir el promedio de uso diario para cualquier día.